// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import gorm "gorm.io/gorm"

// beforeCreate runs before the InstrumentationAgentDefinition is created.
func (i *InstrumentationAgentDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the InstrumentationAgentDefinition is updated.
func (i *InstrumentationAgentDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the InstrumentationAgentDefinition is deleted.
func (i *InstrumentationAgentDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the InstrumentationAgentDefinition is created.
func (i *InstrumentationAgentDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the InstrumentationAgentDefinition is updated.
func (i *InstrumentationAgentDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the InstrumentationAgentDefinition is deleted.
func (i *InstrumentationAgentDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the InstrumentationAgentInstance is created.
func (i *InstrumentationAgentInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the InstrumentationAgentInstance is updated.
func (i *InstrumentationAgentInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the InstrumentationAgentInstance is deleted.
func (i *InstrumentationAgentInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the InstrumentationAgentInstance is created.
func (i *InstrumentationAgentInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the InstrumentationAgentInstance is updated.
func (i *InstrumentationAgentInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the InstrumentationAgentInstance is deleted.
func (i *InstrumentationAgentInstance) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the InstrumentationBrowserRelayDefinition is created.
func (i *InstrumentationBrowserRelayDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the InstrumentationBrowserRelayDefinition is updated.
func (i *InstrumentationBrowserRelayDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the InstrumentationBrowserRelayDefinition is deleted.
func (i *InstrumentationBrowserRelayDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the InstrumentationBrowserRelayDefinition is created.
func (i *InstrumentationBrowserRelayDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the InstrumentationBrowserRelayDefinition is updated.
func (i *InstrumentationBrowserRelayDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the InstrumentationBrowserRelayDefinition is deleted.
func (i *InstrumentationBrowserRelayDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the InstrumentationBrowserRelayInstance is created.
func (i *InstrumentationBrowserRelayInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the InstrumentationBrowserRelayInstance is updated.
func (i *InstrumentationBrowserRelayInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the InstrumentationBrowserRelayInstance is deleted.
func (i *InstrumentationBrowserRelayInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the InstrumentationBrowserRelayInstance is created.
func (i *InstrumentationBrowserRelayInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the InstrumentationBrowserRelayInstance is updated.
func (i *InstrumentationBrowserRelayInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the InstrumentationBrowserRelayInstance is deleted.
func (i *InstrumentationBrowserRelayInstance) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the InstrumentationGatewayDefinition is created.
func (i *InstrumentationGatewayDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the InstrumentationGatewayDefinition is updated.
func (i *InstrumentationGatewayDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the InstrumentationGatewayDefinition is deleted.
func (i *InstrumentationGatewayDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the InstrumentationGatewayDefinition is created.
func (i *InstrumentationGatewayDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the InstrumentationGatewayDefinition is updated.
func (i *InstrumentationGatewayDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the InstrumentationGatewayDefinition is deleted.
func (i *InstrumentationGatewayDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the InstrumentationGatewayInstance is created.
func (i *InstrumentationGatewayInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the InstrumentationGatewayInstance is updated.
func (i *InstrumentationGatewayInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the InstrumentationGatewayInstance is deleted.
func (i *InstrumentationGatewayInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the InstrumentationGatewayInstance is created.
func (i *InstrumentationGatewayInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the InstrumentationGatewayInstance is updated.
func (i *InstrumentationGatewayInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the InstrumentationGatewayInstance is deleted.
func (i *InstrumentationGatewayInstance) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the LoggingDefinition is created.
func (l *LoggingDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the LoggingDefinition is updated.
func (l *LoggingDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the LoggingDefinition is deleted.
func (l *LoggingDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the LoggingDefinition is created.
func (l *LoggingDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the LoggingDefinition is updated.
func (l *LoggingDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the LoggingDefinition is deleted.
func (l *LoggingDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the LoggingInstance is created.
func (l *LoggingInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the LoggingInstance is updated.
func (l *LoggingInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the LoggingInstance is deleted.
func (l *LoggingInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the LoggingInstance is created.
func (l *LoggingInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the LoggingInstance is updated.
func (l *LoggingInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the LoggingInstance is deleted.
func (l *LoggingInstance) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the MetricsDefinition is created.
func (m *MetricsDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the MetricsDefinition is updated.
func (m *MetricsDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the MetricsDefinition is deleted.
func (m *MetricsDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the MetricsDefinition is created.
func (m *MetricsDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the MetricsDefinition is updated.
func (m *MetricsDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the MetricsDefinition is deleted.
func (m *MetricsDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the MetricsInstance is created.
func (m *MetricsInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the MetricsInstance is updated.
func (m *MetricsInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the MetricsInstance is deleted.
func (m *MetricsInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the MetricsInstance is created.
func (m *MetricsInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the MetricsInstance is updated.
func (m *MetricsInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the MetricsInstance is deleted.
func (m *MetricsInstance) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the ObservabilityDashboardDefinition is created.
func (o *ObservabilityDashboardDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the ObservabilityDashboardDefinition is updated.
func (o *ObservabilityDashboardDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the ObservabilityDashboardDefinition is deleted.
func (o *ObservabilityDashboardDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the ObservabilityDashboardDefinition is created.
func (o *ObservabilityDashboardDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the ObservabilityDashboardDefinition is updated.
func (o *ObservabilityDashboardDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the ObservabilityDashboardDefinition is deleted.
func (o *ObservabilityDashboardDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the ObservabilityDashboardInstance is created.
func (o *ObservabilityDashboardInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the ObservabilityDashboardInstance is updated.
func (o *ObservabilityDashboardInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the ObservabilityDashboardInstance is deleted.
func (o *ObservabilityDashboardInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the ObservabilityDashboardInstance is created.
func (o *ObservabilityDashboardInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the ObservabilityDashboardInstance is updated.
func (o *ObservabilityDashboardInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the ObservabilityDashboardInstance is deleted.
func (o *ObservabilityDashboardInstance) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the ObservabilityStackDefinition is created.
func (o *ObservabilityStackDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the ObservabilityStackDefinition is updated.
func (o *ObservabilityStackDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the ObservabilityStackDefinition is deleted.
func (o *ObservabilityStackDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the ObservabilityStackDefinition is created.
func (o *ObservabilityStackDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the ObservabilityStackDefinition is updated.
func (o *ObservabilityStackDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the ObservabilityStackDefinition is deleted.
func (o *ObservabilityStackDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the ObservabilityStackInstance is created.
func (o *ObservabilityStackInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the ObservabilityStackInstance is updated.
func (o *ObservabilityStackInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the ObservabilityStackInstance is deleted.
func (o *ObservabilityStackInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the ObservabilityStackInstance is created.
func (o *ObservabilityStackInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the ObservabilityStackInstance is updated.
func (o *ObservabilityStackInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the ObservabilityStackInstance is deleted.
func (o *ObservabilityStackInstance) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the TracingDefinition is created.
func (t *TracingDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the TracingDefinition is updated.
func (t *TracingDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the TracingDefinition is deleted.
func (t *TracingDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the TracingDefinition is created.
func (t *TracingDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the TracingDefinition is updated.
func (t *TracingDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the TracingDefinition is deleted.
func (t *TracingDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the TracingInstance is created.
func (t *TracingInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the TracingInstance is updated.
func (t *TracingInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the TracingInstance is deleted.
func (t *TracingInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the TracingInstance is created.
func (t *TracingInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the TracingInstance is updated.
func (t *TracingInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the TracingInstance is deleted.
func (t *TracingInstance) afterDelete(tx *gorm.DB) error {
	return nil
}
