// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import gorm "gorm.io/gorm"

// BeforeCreate is the GORM before-create hook for InstrumentationAgentDefinition.
func (i *InstrumentationAgentDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := i.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, i)
}

// BeforeUpdate is the GORM before-update hook for InstrumentationAgentDefinition.
func (i *InstrumentationAgentDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := i.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, i)
}

// BeforeDelete is the GORM before-delete hook for InstrumentationAgentDefinition.
func (i *InstrumentationAgentDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := i.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, i)
}

// AfterCreate is the GORM after-create hook for InstrumentationAgentDefinition.
func (i *InstrumentationAgentDefinition) AfterCreate(tx *gorm.DB) error {
	if err := i.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, i)
}

// AfterUpdate is the GORM after-update hook for InstrumentationAgentDefinition.
func (i *InstrumentationAgentDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := i.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, i)
}

// AfterDelete is the GORM after-delete hook for InstrumentationAgentDefinition.
func (i *InstrumentationAgentDefinition) AfterDelete(tx *gorm.DB) error {
	if err := i.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, i)
}

// BeforeCreate is the GORM before-create hook for InstrumentationAgentInstance.
func (i *InstrumentationAgentInstance) BeforeCreate(tx *gorm.DB) error {
	if err := i.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, i)
}

// BeforeUpdate is the GORM before-update hook for InstrumentationAgentInstance.
func (i *InstrumentationAgentInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := i.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, i)
}

// BeforeDelete is the GORM before-delete hook for InstrumentationAgentInstance.
func (i *InstrumentationAgentInstance) BeforeDelete(tx *gorm.DB) error {
	if err := i.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, i)
}

// AfterCreate is the GORM after-create hook for InstrumentationAgentInstance.
func (i *InstrumentationAgentInstance) AfterCreate(tx *gorm.DB) error {
	if err := i.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, i)
}

// AfterUpdate is the GORM after-update hook for InstrumentationAgentInstance.
func (i *InstrumentationAgentInstance) AfterUpdate(tx *gorm.DB) error {
	if err := i.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, i)
}

// AfterDelete is the GORM after-delete hook for InstrumentationAgentInstance.
func (i *InstrumentationAgentInstance) AfterDelete(tx *gorm.DB) error {
	if err := i.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, i)
}

// BeforeCreate is the GORM before-create hook for InstrumentationBrowserRelayDefinition.
func (i *InstrumentationBrowserRelayDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := i.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, i)
}

// BeforeUpdate is the GORM before-update hook for InstrumentationBrowserRelayDefinition.
func (i *InstrumentationBrowserRelayDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := i.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, i)
}

// BeforeDelete is the GORM before-delete hook for InstrumentationBrowserRelayDefinition.
func (i *InstrumentationBrowserRelayDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := i.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, i)
}

// AfterCreate is the GORM after-create hook for InstrumentationBrowserRelayDefinition.
func (i *InstrumentationBrowserRelayDefinition) AfterCreate(tx *gorm.DB) error {
	if err := i.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, i)
}

// AfterUpdate is the GORM after-update hook for InstrumentationBrowserRelayDefinition.
func (i *InstrumentationBrowserRelayDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := i.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, i)
}

// AfterDelete is the GORM after-delete hook for InstrumentationBrowserRelayDefinition.
func (i *InstrumentationBrowserRelayDefinition) AfterDelete(tx *gorm.DB) error {
	if err := i.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, i)
}

// BeforeCreate is the GORM before-create hook for InstrumentationBrowserRelayInstance.
func (i *InstrumentationBrowserRelayInstance) BeforeCreate(tx *gorm.DB) error {
	if err := i.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, i)
}

// BeforeUpdate is the GORM before-update hook for InstrumentationBrowserRelayInstance.
func (i *InstrumentationBrowserRelayInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := i.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, i)
}

// BeforeDelete is the GORM before-delete hook for InstrumentationBrowserRelayInstance.
func (i *InstrumentationBrowserRelayInstance) BeforeDelete(tx *gorm.DB) error {
	if err := i.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, i)
}

// AfterCreate is the GORM after-create hook for InstrumentationBrowserRelayInstance.
func (i *InstrumentationBrowserRelayInstance) AfterCreate(tx *gorm.DB) error {
	if err := i.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, i)
}

// AfterUpdate is the GORM after-update hook for InstrumentationBrowserRelayInstance.
func (i *InstrumentationBrowserRelayInstance) AfterUpdate(tx *gorm.DB) error {
	if err := i.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, i)
}

// AfterDelete is the GORM after-delete hook for InstrumentationBrowserRelayInstance.
func (i *InstrumentationBrowserRelayInstance) AfterDelete(tx *gorm.DB) error {
	if err := i.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, i)
}

// BeforeCreate is the GORM before-create hook for InstrumentationGatewayDefinition.
func (i *InstrumentationGatewayDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := i.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, i)
}

// BeforeUpdate is the GORM before-update hook for InstrumentationGatewayDefinition.
func (i *InstrumentationGatewayDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := i.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, i)
}

// BeforeDelete is the GORM before-delete hook for InstrumentationGatewayDefinition.
func (i *InstrumentationGatewayDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := i.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, i)
}

// AfterCreate is the GORM after-create hook for InstrumentationGatewayDefinition.
func (i *InstrumentationGatewayDefinition) AfterCreate(tx *gorm.DB) error {
	if err := i.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, i)
}

// AfterUpdate is the GORM after-update hook for InstrumentationGatewayDefinition.
func (i *InstrumentationGatewayDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := i.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, i)
}

// AfterDelete is the GORM after-delete hook for InstrumentationGatewayDefinition.
func (i *InstrumentationGatewayDefinition) AfterDelete(tx *gorm.DB) error {
	if err := i.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, i)
}

// BeforeCreate is the GORM before-create hook for InstrumentationGatewayInstance.
func (i *InstrumentationGatewayInstance) BeforeCreate(tx *gorm.DB) error {
	if err := i.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, i)
}

// BeforeUpdate is the GORM before-update hook for InstrumentationGatewayInstance.
func (i *InstrumentationGatewayInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := i.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, i)
}

// BeforeDelete is the GORM before-delete hook for InstrumentationGatewayInstance.
func (i *InstrumentationGatewayInstance) BeforeDelete(tx *gorm.DB) error {
	if err := i.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, i)
}

// AfterCreate is the GORM after-create hook for InstrumentationGatewayInstance.
func (i *InstrumentationGatewayInstance) AfterCreate(tx *gorm.DB) error {
	if err := i.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, i)
}

// AfterUpdate is the GORM after-update hook for InstrumentationGatewayInstance.
func (i *InstrumentationGatewayInstance) AfterUpdate(tx *gorm.DB) error {
	if err := i.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, i)
}

// AfterDelete is the GORM after-delete hook for InstrumentationGatewayInstance.
func (i *InstrumentationGatewayInstance) AfterDelete(tx *gorm.DB) error {
	if err := i.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, i)
}

// BeforeCreate is the GORM before-create hook for LoggingDefinition.
func (l *LoggingDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := l.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, l)
}

// BeforeUpdate is the GORM before-update hook for LoggingDefinition.
func (l *LoggingDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := l.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, l)
}

// BeforeDelete is the GORM before-delete hook for LoggingDefinition.
func (l *LoggingDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := l.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, l)
}

// AfterCreate is the GORM after-create hook for LoggingDefinition.
func (l *LoggingDefinition) AfterCreate(tx *gorm.DB) error {
	if err := l.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, l)
}

// AfterUpdate is the GORM after-update hook for LoggingDefinition.
func (l *LoggingDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := l.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, l)
}

// AfterDelete is the GORM after-delete hook for LoggingDefinition.
func (l *LoggingDefinition) AfterDelete(tx *gorm.DB) error {
	if err := l.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, l)
}

// BeforeCreate is the GORM before-create hook for LoggingInstance.
func (l *LoggingInstance) BeforeCreate(tx *gorm.DB) error {
	if err := l.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, l)
}

// BeforeUpdate is the GORM before-update hook for LoggingInstance.
func (l *LoggingInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := l.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, l)
}

// BeforeDelete is the GORM before-delete hook for LoggingInstance.
func (l *LoggingInstance) BeforeDelete(tx *gorm.DB) error {
	if err := l.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, l)
}

// AfterCreate is the GORM after-create hook for LoggingInstance.
func (l *LoggingInstance) AfterCreate(tx *gorm.DB) error {
	if err := l.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, l)
}

// AfterUpdate is the GORM after-update hook for LoggingInstance.
func (l *LoggingInstance) AfterUpdate(tx *gorm.DB) error {
	if err := l.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, l)
}

// AfterDelete is the GORM after-delete hook for LoggingInstance.
func (l *LoggingInstance) AfterDelete(tx *gorm.DB) error {
	if err := l.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, l)
}

// BeforeCreate is the GORM before-create hook for MetricsDefinition.
func (m *MetricsDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := m.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, m)
}

// BeforeUpdate is the GORM before-update hook for MetricsDefinition.
func (m *MetricsDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := m.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, m)
}

// BeforeDelete is the GORM before-delete hook for MetricsDefinition.
func (m *MetricsDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := m.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, m)
}

// AfterCreate is the GORM after-create hook for MetricsDefinition.
func (m *MetricsDefinition) AfterCreate(tx *gorm.DB) error {
	if err := m.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, m)
}

// AfterUpdate is the GORM after-update hook for MetricsDefinition.
func (m *MetricsDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := m.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, m)
}

// AfterDelete is the GORM after-delete hook for MetricsDefinition.
func (m *MetricsDefinition) AfterDelete(tx *gorm.DB) error {
	if err := m.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, m)
}

// BeforeCreate is the GORM before-create hook for MetricsInstance.
func (m *MetricsInstance) BeforeCreate(tx *gorm.DB) error {
	if err := m.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, m)
}

// BeforeUpdate is the GORM before-update hook for MetricsInstance.
func (m *MetricsInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := m.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, m)
}

// BeforeDelete is the GORM before-delete hook for MetricsInstance.
func (m *MetricsInstance) BeforeDelete(tx *gorm.DB) error {
	if err := m.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, m)
}

// AfterCreate is the GORM after-create hook for MetricsInstance.
func (m *MetricsInstance) AfterCreate(tx *gorm.DB) error {
	if err := m.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, m)
}

// AfterUpdate is the GORM after-update hook for MetricsInstance.
func (m *MetricsInstance) AfterUpdate(tx *gorm.DB) error {
	if err := m.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, m)
}

// AfterDelete is the GORM after-delete hook for MetricsInstance.
func (m *MetricsInstance) AfterDelete(tx *gorm.DB) error {
	if err := m.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, m)
}

// BeforeCreate is the GORM before-create hook for MetricsStorageDefinition.
func (m *MetricsStorageDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := m.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, m)
}

// BeforeUpdate is the GORM before-update hook for MetricsStorageDefinition.
func (m *MetricsStorageDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := m.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, m)
}

// BeforeDelete is the GORM before-delete hook for MetricsStorageDefinition.
func (m *MetricsStorageDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := m.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, m)
}

// AfterCreate is the GORM after-create hook for MetricsStorageDefinition.
func (m *MetricsStorageDefinition) AfterCreate(tx *gorm.DB) error {
	if err := m.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, m)
}

// AfterUpdate is the GORM after-update hook for MetricsStorageDefinition.
func (m *MetricsStorageDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := m.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, m)
}

// AfterDelete is the GORM after-delete hook for MetricsStorageDefinition.
func (m *MetricsStorageDefinition) AfterDelete(tx *gorm.DB) error {
	if err := m.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, m)
}

// BeforeCreate is the GORM before-create hook for MetricsStorageInstance.
func (m *MetricsStorageInstance) BeforeCreate(tx *gorm.DB) error {
	if err := m.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, m)
}

// BeforeUpdate is the GORM before-update hook for MetricsStorageInstance.
func (m *MetricsStorageInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := m.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, m)
}

// BeforeDelete is the GORM before-delete hook for MetricsStorageInstance.
func (m *MetricsStorageInstance) BeforeDelete(tx *gorm.DB) error {
	if err := m.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, m)
}

// AfterCreate is the GORM after-create hook for MetricsStorageInstance.
func (m *MetricsStorageInstance) AfterCreate(tx *gorm.DB) error {
	if err := m.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, m)
}

// AfterUpdate is the GORM after-update hook for MetricsStorageInstance.
func (m *MetricsStorageInstance) AfterUpdate(tx *gorm.DB) error {
	if err := m.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, m)
}

// AfterDelete is the GORM after-delete hook for MetricsStorageInstance.
func (m *MetricsStorageInstance) AfterDelete(tx *gorm.DB) error {
	if err := m.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, m)
}

// BeforeCreate is the GORM before-create hook for ObservabilityDashboardDefinition.
func (o *ObservabilityDashboardDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := o.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, o)
}

// BeforeUpdate is the GORM before-update hook for ObservabilityDashboardDefinition.
func (o *ObservabilityDashboardDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := o.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, o)
}

// BeforeDelete is the GORM before-delete hook for ObservabilityDashboardDefinition.
func (o *ObservabilityDashboardDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := o.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, o)
}

// AfterCreate is the GORM after-create hook for ObservabilityDashboardDefinition.
func (o *ObservabilityDashboardDefinition) AfterCreate(tx *gorm.DB) error {
	if err := o.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, o)
}

// AfterUpdate is the GORM after-update hook for ObservabilityDashboardDefinition.
func (o *ObservabilityDashboardDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := o.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, o)
}

// AfterDelete is the GORM after-delete hook for ObservabilityDashboardDefinition.
func (o *ObservabilityDashboardDefinition) AfterDelete(tx *gorm.DB) error {
	if err := o.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, o)
}

// BeforeCreate is the GORM before-create hook for ObservabilityDashboardInstance.
func (o *ObservabilityDashboardInstance) BeforeCreate(tx *gorm.DB) error {
	if err := o.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, o)
}

// BeforeUpdate is the GORM before-update hook for ObservabilityDashboardInstance.
func (o *ObservabilityDashboardInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := o.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, o)
}

// BeforeDelete is the GORM before-delete hook for ObservabilityDashboardInstance.
func (o *ObservabilityDashboardInstance) BeforeDelete(tx *gorm.DB) error {
	if err := o.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, o)
}

// AfterCreate is the GORM after-create hook for ObservabilityDashboardInstance.
func (o *ObservabilityDashboardInstance) AfterCreate(tx *gorm.DB) error {
	if err := o.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, o)
}

// AfterUpdate is the GORM after-update hook for ObservabilityDashboardInstance.
func (o *ObservabilityDashboardInstance) AfterUpdate(tx *gorm.DB) error {
	if err := o.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, o)
}

// AfterDelete is the GORM after-delete hook for ObservabilityDashboardInstance.
func (o *ObservabilityDashboardInstance) AfterDelete(tx *gorm.DB) error {
	if err := o.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, o)
}

// BeforeCreate is the GORM before-create hook for ObservabilityStackDefinition.
func (o *ObservabilityStackDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := o.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, o)
}

// BeforeUpdate is the GORM before-update hook for ObservabilityStackDefinition.
func (o *ObservabilityStackDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := o.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, o)
}

// BeforeDelete is the GORM before-delete hook for ObservabilityStackDefinition.
func (o *ObservabilityStackDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := o.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, o)
}

// AfterCreate is the GORM after-create hook for ObservabilityStackDefinition.
func (o *ObservabilityStackDefinition) AfterCreate(tx *gorm.DB) error {
	if err := o.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, o)
}

// AfterUpdate is the GORM after-update hook for ObservabilityStackDefinition.
func (o *ObservabilityStackDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := o.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, o)
}

// AfterDelete is the GORM after-delete hook for ObservabilityStackDefinition.
func (o *ObservabilityStackDefinition) AfterDelete(tx *gorm.DB) error {
	if err := o.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, o)
}

// BeforeCreate is the GORM before-create hook for ObservabilityStackInstance.
func (o *ObservabilityStackInstance) BeforeCreate(tx *gorm.DB) error {
	if err := o.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, o)
}

// BeforeUpdate is the GORM before-update hook for ObservabilityStackInstance.
func (o *ObservabilityStackInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := o.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, o)
}

// BeforeDelete is the GORM before-delete hook for ObservabilityStackInstance.
func (o *ObservabilityStackInstance) BeforeDelete(tx *gorm.DB) error {
	if err := o.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, o)
}

// AfterCreate is the GORM after-create hook for ObservabilityStackInstance.
func (o *ObservabilityStackInstance) AfterCreate(tx *gorm.DB) error {
	if err := o.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, o)
}

// AfterUpdate is the GORM after-update hook for ObservabilityStackInstance.
func (o *ObservabilityStackInstance) AfterUpdate(tx *gorm.DB) error {
	if err := o.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, o)
}

// AfterDelete is the GORM after-delete hook for ObservabilityStackInstance.
func (o *ObservabilityStackInstance) AfterDelete(tx *gorm.DB) error {
	if err := o.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, o)
}

// BeforeCreate is the GORM before-create hook for TracingDefinition.
func (t *TracingDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := t.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, t)
}

// BeforeUpdate is the GORM before-update hook for TracingDefinition.
func (t *TracingDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := t.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, t)
}

// BeforeDelete is the GORM before-delete hook for TracingDefinition.
func (t *TracingDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := t.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, t)
}

// AfterCreate is the GORM after-create hook for TracingDefinition.
func (t *TracingDefinition) AfterCreate(tx *gorm.DB) error {
	if err := t.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, t)
}

// AfterUpdate is the GORM after-update hook for TracingDefinition.
func (t *TracingDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := t.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, t)
}

// AfterDelete is the GORM after-delete hook for TracingDefinition.
func (t *TracingDefinition) AfterDelete(tx *gorm.DB) error {
	if err := t.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, t)
}

// BeforeCreate is the GORM before-create hook for TracingInstance.
func (t *TracingInstance) BeforeCreate(tx *gorm.DB) error {
	if err := t.beforeCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeCreate(tx, t)
}

// BeforeUpdate is the GORM before-update hook for TracingInstance.
func (t *TracingInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := t.beforeUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeUpdate(tx, t)
}

// BeforeDelete is the GORM before-delete hook for TracingInstance.
func (t *TracingInstance) BeforeDelete(tx *gorm.DB) error {
	if err := t.beforeDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsBeforeDelete(tx, t)
}

// AfterCreate is the GORM after-create hook for TracingInstance.
func (t *TracingInstance) AfterCreate(tx *gorm.DB) error {
	if err := t.afterCreate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterCreate(tx, t)
}

// AfterUpdate is the GORM after-update hook for TracingInstance.
func (t *TracingInstance) AfterUpdate(tx *gorm.DB) error {
	if err := t.afterUpdate(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterUpdate(tx, t)
}

// AfterDelete is the GORM after-delete hook for TracingInstance.
func (t *TracingInstance) AfterDelete(tx *gorm.DB) error {
	if err := t.afterDelete(tx); err != nil {
		return err
	}
	return ProcessCoreTaggedFieldsAfterDelete(tx, t)
}
