// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	"encoding/json"
	"fmt"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
	"time"
)

const (
	ObjectTypeInstrumentationAgentDefinition        string = "InstrumentationAgentDefinition"
	ObjectTypeInstrumentationAgentInstance          string = "InstrumentationAgentInstance"
	ObjectTypeInstrumentationBrowserRelayDefinition string = "InstrumentationBrowserRelayDefinition"
	ObjectTypeInstrumentationBrowserRelayInstance   string = "InstrumentationBrowserRelayInstance"
	ObjectTypeInstrumentationGatewayDefinition      string = "InstrumentationGatewayDefinition"
	ObjectTypeInstrumentationGatewayInstance        string = "InstrumentationGatewayInstance"
	ObjectTypeLoggingDefinition                     string = "LoggingDefinition"
	ObjectTypeLoggingInstance                       string = "LoggingInstance"
	ObjectTypeMetricsDefinition                     string = "MetricsDefinition"
	ObjectTypeMetricsInstance                       string = "MetricsInstance"
	ObjectTypeMetricsStorageDefinition              string = "MetricsStorageDefinition"
	ObjectTypeMetricsStorageInstance                string = "MetricsStorageInstance"
	ObjectTypeObservabilityDashboardDefinition      string = "ObservabilityDashboardDefinition"
	ObjectTypeObservabilityDashboardInstance        string = "ObservabilityDashboardInstance"
	ObjectTypeObservabilityStackDefinition          string = "ObservabilityStackDefinition"
	ObjectTypeObservabilityStackInstance            string = "ObservabilityStackInstance"
	ObjectTypeTracingDefinition                     string = "TracingDefinition"
	ObjectTypeTracingInstance                       string = "TracingInstance"

	PathInstrumentationAgentDefinitionVersions        = "/instrumentation-agent-definitions/versions"
	PathInstrumentationAgentDefinitions               = "/v0/instrumentation-agent-definitions"
	PathInstrumentationAgentInstanceVersions          = "/instrumentation-agent-instances/versions"
	PathInstrumentationAgentInstances                 = "/v0/instrumentation-agent-instances"
	PathInstrumentationBrowserRelayDefinitionVersions = "/instrumentation-browser-relay-definitions/versions"
	PathInstrumentationBrowserRelayDefinitions        = "/v0/instrumentation-browser-relay-definitions"
	PathInstrumentationBrowserRelayInstanceVersions   = "/instrumentation-browser-relay-instances/versions"
	PathInstrumentationBrowserRelayInstances          = "/v0/instrumentation-browser-relay-instances"
	PathInstrumentationGatewayDefinitionVersions      = "/instrumentation-gateway-definitions/versions"
	PathInstrumentationGatewayDefinitions             = "/v0/instrumentation-gateway-definitions"
	PathInstrumentationGatewayInstanceVersions        = "/instrumentation-gateway-instances/versions"
	PathInstrumentationGatewayInstances               = "/v0/instrumentation-gateway-instances"
	PathLoggingDefinitionVersions                     = "/logging-definitions/versions"
	PathLoggingDefinitions                            = "/v0/logging-definitions"
	PathLoggingInstanceVersions                       = "/logging-instances/versions"
	PathLoggingInstances                              = "/v0/logging-instances"
	PathMetricsDefinitionVersions                     = "/metrics-definitions/versions"
	PathMetricsDefinitions                            = "/v0/metrics-definitions"
	PathMetricsInstanceVersions                       = "/metrics-instances/versions"
	PathMetricsInstances                              = "/v0/metrics-instances"
	PathMetricsStorageDefinitionVersions              = "/metrics-storage-definitions/versions"
	PathMetricsStorageDefinitions                     = "/v0/metrics-storage-definitions"
	PathMetricsStorageInstanceVersions                = "/metrics-storage-instances/versions"
	PathMetricsStorageInstances                       = "/v0/metrics-storage-instances"
	PathObservabilityDashboardDefinitionVersions      = "/observability-dashboard-definitions/versions"
	PathObservabilityDashboardDefinitions             = "/v0/observability-dashboard-definitions"
	PathObservabilityDashboardInstanceVersions        = "/observability-dashboard-instances/versions"
	PathObservabilityDashboardInstances               = "/v0/observability-dashboard-instances"
	PathObservabilityStackDefinitionVersions          = "/observability-stack-definitions/versions"
	PathObservabilityStackDefinitions                 = "/v0/observability-stack-definitions"
	PathObservabilityStackInstanceVersions            = "/observability-stack-instances/versions"
	PathObservabilityStackInstances                   = "/v0/observability-stack-instances"
	PathTracingDefinitionVersions                     = "/tracing-definitions/versions"
	PathTracingDefinitions                            = "/v0/tracing-definitions"
	PathTracingInstanceVersions                       = "/tracing-instances/versions"
	PathTracingInstances                              = "/v0/tracing-instances"
)

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (iad *InstrumentationAgentDefinition) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        iad,
		ObjectVersion: iad.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", iad, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (iad *InstrumentationAgentDefinition) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &iad); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (iad *InstrumentationAgentDefinition) GetId() uint {
	return *iad.ID
}

// GetType returns the object type.
func (iad *InstrumentationAgentDefinition) GetType() string {
	return "InstrumentationAgentDefinition"
}

// GetVersion returns the version of the API object.
func (iad *InstrumentationAgentDefinition) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (iad *InstrumentationAgentDefinition) GetFullyQualifiedType() string {
	return "threeport.io/v0.InstrumentationAgentDefinition"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (iad *InstrumentationAgentDefinition) ScheduledForDeletion() *time.Time {
	return iad.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on InstrumentationAgentDefinition.
func (i *InstrumentationAgentDefinition) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "OtelAgentHelmWorkloadDefinitionID",
		ObjectID:     i.OtelAgentHelmWorkloadDefinitionID,
		ObjectType:   new(HelmWorkloadDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (iai *InstrumentationAgentInstance) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        iai,
		ObjectVersion: iai.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", iai, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (iai *InstrumentationAgentInstance) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &iai); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (iai *InstrumentationAgentInstance) GetId() uint {
	return *iai.ID
}

// GetType returns the object type.
func (iai *InstrumentationAgentInstance) GetType() string {
	return "InstrumentationAgentInstance"
}

// GetVersion returns the version of the API object.
func (iai *InstrumentationAgentInstance) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (iai *InstrumentationAgentInstance) GetFullyQualifiedType() string {
	return "threeport.io/v0.InstrumentationAgentInstance"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (iai *InstrumentationAgentInstance) ScheduledForDeletion() *time.Time {
	return iai.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on InstrumentationAgentInstance.
func (i *InstrumentationAgentInstance) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "InstrumentationAgentDefinitionID",
		ObjectID:     i.InstrumentationAgentDefinitionID,
		ObjectType:   new(InstrumentationAgentDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "KubernetesRuntimeInstanceID",
		ObjectID:     i.KubernetesRuntimeInstanceID,
		ObjectType:   new(KubernetesRuntimeInstance).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "OtelAgentHelmWorkloadInstanceID",
		ObjectID:     i.OtelAgentHelmWorkloadInstanceID,
		ObjectType:   new(HelmWorkloadInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (ibrd *InstrumentationBrowserRelayDefinition) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        ibrd,
		ObjectVersion: ibrd.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", ibrd, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (ibrd *InstrumentationBrowserRelayDefinition) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &ibrd); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (ibrd *InstrumentationBrowserRelayDefinition) GetId() uint {
	return *ibrd.ID
}

// GetType returns the object type.
func (ibrd *InstrumentationBrowserRelayDefinition) GetType() string {
	return "InstrumentationBrowserRelayDefinition"
}

// GetVersion returns the version of the API object.
func (ibrd *InstrumentationBrowserRelayDefinition) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (ibrd *InstrumentationBrowserRelayDefinition) GetFullyQualifiedType() string {
	return "threeport.io/v0.InstrumentationBrowserRelayDefinition"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (ibrd *InstrumentationBrowserRelayDefinition) ScheduledForDeletion() *time.Time {
	return ibrd.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on InstrumentationBrowserRelayDefinition.
func (i *InstrumentationBrowserRelayDefinition) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "OtelBrowserRelayHelmWorkloadDefinitionID",
		ObjectID:     i.OtelBrowserRelayHelmWorkloadDefinitionID,
		ObjectType:   new(HelmWorkloadDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (ibri *InstrumentationBrowserRelayInstance) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        ibri,
		ObjectVersion: ibri.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", ibri, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (ibri *InstrumentationBrowserRelayInstance) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &ibri); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (ibri *InstrumentationBrowserRelayInstance) GetId() uint {
	return *ibri.ID
}

// GetType returns the object type.
func (ibri *InstrumentationBrowserRelayInstance) GetType() string {
	return "InstrumentationBrowserRelayInstance"
}

// GetVersion returns the version of the API object.
func (ibri *InstrumentationBrowserRelayInstance) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (ibri *InstrumentationBrowserRelayInstance) GetFullyQualifiedType() string {
	return "threeport.io/v0.InstrumentationBrowserRelayInstance"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (ibri *InstrumentationBrowserRelayInstance) ScheduledForDeletion() *time.Time {
	return ibri.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on InstrumentationBrowserRelayInstance.
func (i *InstrumentationBrowserRelayInstance) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "InstrumentationBrowserRelayDefinitionID",
		ObjectID:     i.InstrumentationBrowserRelayDefinitionID,
		ObjectType:   new(InstrumentationBrowserRelayDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "KubernetesRuntimeInstanceID",
		ObjectID:     i.KubernetesRuntimeInstanceID,
		ObjectType:   new(KubernetesRuntimeInstance).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "OtelBrowserRelayHelmWorkloadInstanceID",
		ObjectID:     i.OtelBrowserRelayHelmWorkloadInstanceID,
		ObjectType:   new(HelmWorkloadInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (igd *InstrumentationGatewayDefinition) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        igd,
		ObjectVersion: igd.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", igd, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (igd *InstrumentationGatewayDefinition) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &igd); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (igd *InstrumentationGatewayDefinition) GetId() uint {
	return *igd.ID
}

// GetType returns the object type.
func (igd *InstrumentationGatewayDefinition) GetType() string {
	return "InstrumentationGatewayDefinition"
}

// GetVersion returns the version of the API object.
func (igd *InstrumentationGatewayDefinition) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (igd *InstrumentationGatewayDefinition) GetFullyQualifiedType() string {
	return "threeport.io/v0.InstrumentationGatewayDefinition"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (igd *InstrumentationGatewayDefinition) ScheduledForDeletion() *time.Time {
	return igd.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on InstrumentationGatewayDefinition.
func (i *InstrumentationGatewayDefinition) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "OtelGatewayHelmWorkloadDefinitionID",
		ObjectID:     i.OtelGatewayHelmWorkloadDefinitionID,
		ObjectType:   new(HelmWorkloadDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (igi *InstrumentationGatewayInstance) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        igi,
		ObjectVersion: igi.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", igi, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (igi *InstrumentationGatewayInstance) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &igi); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (igi *InstrumentationGatewayInstance) GetId() uint {
	return *igi.ID
}

// GetType returns the object type.
func (igi *InstrumentationGatewayInstance) GetType() string {
	return "InstrumentationGatewayInstance"
}

// GetVersion returns the version of the API object.
func (igi *InstrumentationGatewayInstance) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (igi *InstrumentationGatewayInstance) GetFullyQualifiedType() string {
	return "threeport.io/v0.InstrumentationGatewayInstance"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (igi *InstrumentationGatewayInstance) ScheduledForDeletion() *time.Time {
	return igi.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on InstrumentationGatewayInstance.
func (i *InstrumentationGatewayInstance) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "InstrumentationGatewayDefinitionID",
		ObjectID:     i.InstrumentationGatewayDefinitionID,
		ObjectType:   new(InstrumentationGatewayDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "KubernetesRuntimeInstanceID",
		ObjectID:     i.KubernetesRuntimeInstanceID,
		ObjectType:   new(KubernetesRuntimeInstance).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "OtelGatewayHelmWorkloadInstanceID",
		ObjectID:     i.OtelGatewayHelmWorkloadInstanceID,
		ObjectType:   new(HelmWorkloadInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (ld *LoggingDefinition) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        ld,
		ObjectVersion: ld.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", ld, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (ld *LoggingDefinition) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &ld); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (ld *LoggingDefinition) GetId() uint {
	return *ld.ID
}

// GetType returns the object type.
func (ld *LoggingDefinition) GetType() string {
	return "LoggingDefinition"
}

// GetVersion returns the version of the API object.
func (ld *LoggingDefinition) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (ld *LoggingDefinition) GetFullyQualifiedType() string {
	return "threeport.io/v0.LoggingDefinition"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (ld *LoggingDefinition) ScheduledForDeletion() *time.Time {
	return ld.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on LoggingDefinition.
func (l *LoggingDefinition) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "LokiHelmWorkloadDefinitionID",
		ObjectID:     l.LokiHelmWorkloadDefinitionID,
		ObjectType:   new(HelmWorkloadDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (li *LoggingInstance) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        li,
		ObjectVersion: li.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", li, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (li *LoggingInstance) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &li); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (li *LoggingInstance) GetId() uint {
	return *li.ID
}

// GetType returns the object type.
func (li *LoggingInstance) GetType() string {
	return "LoggingInstance"
}

// GetVersion returns the version of the API object.
func (li *LoggingInstance) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (li *LoggingInstance) GetFullyQualifiedType() string {
	return "threeport.io/v0.LoggingInstance"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (li *LoggingInstance) ScheduledForDeletion() *time.Time {
	return li.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on LoggingInstance.
func (l *LoggingInstance) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "KubernetesRuntimeInstanceID",
		ObjectID:     l.KubernetesRuntimeInstanceID,
		ObjectType:   new(KubernetesRuntimeInstance).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "LoggingDefinitionID",
		ObjectID:     l.LoggingDefinitionID,
		ObjectType:   new(LoggingDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "LokiHelmWorkloadInstanceID",
		ObjectID:     l.LokiHelmWorkloadInstanceID,
		ObjectType:   new(HelmWorkloadInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (md *MetricsDefinition) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        md,
		ObjectVersion: md.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", md, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (md *MetricsDefinition) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &md); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (md *MetricsDefinition) GetId() uint {
	return *md.ID
}

// GetType returns the object type.
func (md *MetricsDefinition) GetType() string {
	return "MetricsDefinition"
}

// GetVersion returns the version of the API object.
func (md *MetricsDefinition) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (md *MetricsDefinition) GetFullyQualifiedType() string {
	return "threeport.io/v0.MetricsDefinition"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (md *MetricsDefinition) ScheduledForDeletion() *time.Time {
	return md.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on MetricsDefinition.
func (m *MetricsDefinition) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "KubePrometheusStackHelmWorkloadDefinitionID",
		ObjectID:     m.KubePrometheusStackHelmWorkloadDefinitionID,
		ObjectType:   new(HelmWorkloadDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (mi *MetricsInstance) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        mi,
		ObjectVersion: mi.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", mi, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (mi *MetricsInstance) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &mi); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (mi *MetricsInstance) GetId() uint {
	return *mi.ID
}

// GetType returns the object type.
func (mi *MetricsInstance) GetType() string {
	return "MetricsInstance"
}

// GetVersion returns the version of the API object.
func (mi *MetricsInstance) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (mi *MetricsInstance) GetFullyQualifiedType() string {
	return "threeport.io/v0.MetricsInstance"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (mi *MetricsInstance) ScheduledForDeletion() *time.Time {
	return mi.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on MetricsInstance.
func (m *MetricsInstance) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "KubePrometheusStackHelmWorkloadInstanceID",
		ObjectID:     m.KubePrometheusStackHelmWorkloadInstanceID,
		ObjectType:   new(HelmWorkloadInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "KubernetesRuntimeInstanceID",
		ObjectID:     m.KubernetesRuntimeInstanceID,
		ObjectType:   new(KubernetesRuntimeInstance).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "MetricsDefinitionID",
		ObjectID:     m.MetricsDefinitionID,
		ObjectType:   new(MetricsDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (msd *MetricsStorageDefinition) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        msd,
		ObjectVersion: msd.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", msd, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (msd *MetricsStorageDefinition) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &msd); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (msd *MetricsStorageDefinition) GetId() uint {
	return *msd.ID
}

// GetType returns the object type.
func (msd *MetricsStorageDefinition) GetType() string {
	return "MetricsStorageDefinition"
}

// GetVersion returns the version of the API object.
func (msd *MetricsStorageDefinition) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (msd *MetricsStorageDefinition) GetFullyQualifiedType() string {
	return "threeport.io/v0.MetricsStorageDefinition"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (msd *MetricsStorageDefinition) ScheduledForDeletion() *time.Time {
	return msd.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on MetricsStorageDefinition.
func (m *MetricsStorageDefinition) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "MimirHelmWorkloadDefinitionID",
		ObjectID:     m.MimirHelmWorkloadDefinitionID,
		ObjectType:   new(HelmWorkloadDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (msi *MetricsStorageInstance) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        msi,
		ObjectVersion: msi.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", msi, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (msi *MetricsStorageInstance) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &msi); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (msi *MetricsStorageInstance) GetId() uint {
	return *msi.ID
}

// GetType returns the object type.
func (msi *MetricsStorageInstance) GetType() string {
	return "MetricsStorageInstance"
}

// GetVersion returns the version of the API object.
func (msi *MetricsStorageInstance) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (msi *MetricsStorageInstance) GetFullyQualifiedType() string {
	return "threeport.io/v0.MetricsStorageInstance"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (msi *MetricsStorageInstance) ScheduledForDeletion() *time.Time {
	return msi.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on MetricsStorageInstance.
func (m *MetricsStorageInstance) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "KubernetesRuntimeInstanceID",
		ObjectID:     m.KubernetesRuntimeInstanceID,
		ObjectType:   new(KubernetesRuntimeInstance).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "MetricsStorageDefinitionID",
		ObjectID:     m.MetricsStorageDefinitionID,
		ObjectType:   new(MetricsStorageDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "MimirHelmWorkloadInstanceID",
		ObjectID:     m.MimirHelmWorkloadInstanceID,
		ObjectType:   new(HelmWorkloadInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (odd *ObservabilityDashboardDefinition) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        odd,
		ObjectVersion: odd.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", odd, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (odd *ObservabilityDashboardDefinition) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &odd); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (odd *ObservabilityDashboardDefinition) GetId() uint {
	return *odd.ID
}

// GetType returns the object type.
func (odd *ObservabilityDashboardDefinition) GetType() string {
	return "ObservabilityDashboardDefinition"
}

// GetVersion returns the version of the API object.
func (odd *ObservabilityDashboardDefinition) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (odd *ObservabilityDashboardDefinition) GetFullyQualifiedType() string {
	return "threeport.io/v0.ObservabilityDashboardDefinition"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (odd *ObservabilityDashboardDefinition) ScheduledForDeletion() *time.Time {
	return odd.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on ObservabilityDashboardDefinition.
func (o *ObservabilityDashboardDefinition) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "GrafanaHelmWorkloadDefinitionID",
		ObjectID:     o.GrafanaHelmWorkloadDefinitionID,
		ObjectType:   new(HelmWorkloadDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (odi *ObservabilityDashboardInstance) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        odi,
		ObjectVersion: odi.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", odi, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (odi *ObservabilityDashboardInstance) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &odi); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (odi *ObservabilityDashboardInstance) GetId() uint {
	return *odi.ID
}

// GetType returns the object type.
func (odi *ObservabilityDashboardInstance) GetType() string {
	return "ObservabilityDashboardInstance"
}

// GetVersion returns the version of the API object.
func (odi *ObservabilityDashboardInstance) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (odi *ObservabilityDashboardInstance) GetFullyQualifiedType() string {
	return "threeport.io/v0.ObservabilityDashboardInstance"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (odi *ObservabilityDashboardInstance) ScheduledForDeletion() *time.Time {
	return odi.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on ObservabilityDashboardInstance.
func (o *ObservabilityDashboardInstance) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "GrafanaHelmWorkloadInstanceID",
		ObjectID:     o.GrafanaHelmWorkloadInstanceID,
		ObjectType:   new(HelmWorkloadInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "KubernetesRuntimeInstanceID",
		ObjectID:     o.KubernetesRuntimeInstanceID,
		ObjectType:   new(KubernetesRuntimeInstance).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "ObservabilityDashboardDefinitionID",
		ObjectID:     o.ObservabilityDashboardDefinitionID,
		ObjectType:   new(ObservabilityDashboardDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (osd *ObservabilityStackDefinition) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        osd,
		ObjectVersion: osd.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", osd, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (osd *ObservabilityStackDefinition) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &osd); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (osd *ObservabilityStackDefinition) GetId() uint {
	return *osd.ID
}

// GetType returns the object type.
func (osd *ObservabilityStackDefinition) GetType() string {
	return "ObservabilityStackDefinition"
}

// GetVersion returns the version of the API object.
func (osd *ObservabilityStackDefinition) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (osd *ObservabilityStackDefinition) GetFullyQualifiedType() string {
	return "threeport.io/v0.ObservabilityStackDefinition"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (osd *ObservabilityStackDefinition) ScheduledForDeletion() *time.Time {
	return osd.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on ObservabilityStackDefinition.
func (o *ObservabilityStackDefinition) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "InstrumentationAgentDefinitionID",
		ObjectID:     o.InstrumentationAgentDefinitionID,
		ObjectType:   new(InstrumentationAgentDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "InstrumentationBrowserRelayDefinitionID",
		ObjectID:     o.InstrumentationBrowserRelayDefinitionID,
		ObjectType:   new(InstrumentationBrowserRelayDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "InstrumentationGatewayDefinitionID",
		ObjectID:     o.InstrumentationGatewayDefinitionID,
		ObjectType:   new(InstrumentationGatewayDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "LoggingDefinitionID",
		ObjectID:     o.LoggingDefinitionID,
		ObjectType:   new(LoggingDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "MetricsDefinitionID",
		ObjectID:     o.MetricsDefinitionID,
		ObjectType:   new(MetricsDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "MetricsStorageDefinitionID",
		ObjectID:     o.MetricsStorageDefinitionID,
		ObjectType:   new(MetricsStorageDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "ObservabilityDashboardDefinitionID",
		ObjectID:     o.ObservabilityDashboardDefinitionID,
		ObjectType:   new(ObservabilityDashboardDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "TracingDefinitionID",
		ObjectID:     o.TracingDefinitionID,
		ObjectType:   new(TracingDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (osi *ObservabilityStackInstance) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        osi,
		ObjectVersion: osi.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", osi, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (osi *ObservabilityStackInstance) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &osi); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (osi *ObservabilityStackInstance) GetId() uint {
	return *osi.ID
}

// GetType returns the object type.
func (osi *ObservabilityStackInstance) GetType() string {
	return "ObservabilityStackInstance"
}

// GetVersion returns the version of the API object.
func (osi *ObservabilityStackInstance) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (osi *ObservabilityStackInstance) GetFullyQualifiedType() string {
	return "threeport.io/v0.ObservabilityStackInstance"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (osi *ObservabilityStackInstance) ScheduledForDeletion() *time.Time {
	return osi.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on ObservabilityStackInstance.
func (o *ObservabilityStackInstance) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "InstrumentationAgentInstanceID",
		ObjectID:     o.InstrumentationAgentInstanceID,
		ObjectType:   new(InstrumentationAgentInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "InstrumentationBrowserRelayInstanceID",
		ObjectID:     o.InstrumentationBrowserRelayInstanceID,
		ObjectType:   new(InstrumentationBrowserRelayInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "InstrumentationGatewayInstanceID",
		ObjectID:     o.InstrumentationGatewayInstanceID,
		ObjectType:   new(InstrumentationGatewayInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "KubernetesRuntimeInstanceID",
		ObjectID:     o.KubernetesRuntimeInstanceID,
		ObjectType:   new(KubernetesRuntimeInstance).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "LoggingInstanceID",
		ObjectID:     o.LoggingInstanceID,
		ObjectType:   new(LoggingInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "MetricsInstanceID",
		ObjectID:     o.MetricsInstanceID,
		ObjectType:   new(MetricsInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "MetricsStorageInstanceID",
		ObjectID:     o.MetricsStorageInstanceID,
		ObjectType:   new(MetricsStorageInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "ObservabilityDashboardInstanceID",
		ObjectID:     o.ObservabilityDashboardInstanceID,
		ObjectType:   new(ObservabilityDashboardInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "ObservabilityStackDefinitionID",
		ObjectID:     o.ObservabilityStackDefinitionID,
		ObjectType:   new(ObservabilityStackDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "TracingInstanceID",
		ObjectID:     o.TracingInstanceID,
		ObjectType:   new(TracingInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (td *TracingDefinition) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        td,
		ObjectVersion: td.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", td, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (td *TracingDefinition) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &td); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (td *TracingDefinition) GetId() uint {
	return *td.ID
}

// GetType returns the object type.
func (td *TracingDefinition) GetType() string {
	return "TracingDefinition"
}

// GetVersion returns the version of the API object.
func (td *TracingDefinition) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (td *TracingDefinition) GetFullyQualifiedType() string {
	return "threeport.io/v0.TracingDefinition"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (td *TracingDefinition) ScheduledForDeletion() *time.Time {
	return td.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on TracingDefinition.
func (t *TracingDefinition) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "TempoHelmWorkloadDefinitionID",
		ObjectID:     t.TempoHelmWorkloadDefinitionID,
		ObjectType:   new(HelmWorkloadDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (ti *TracingInstance) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        ti,
		ObjectVersion: ti.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", ti, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (ti *TracingInstance) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &ti); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (ti *TracingInstance) GetId() uint {
	return *ti.ID
}

// GetType returns the object type.
func (ti *TracingInstance) GetType() string {
	return "TracingInstance"
}

// GetVersion returns the version of the API object.
func (ti *TracingInstance) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (ti *TracingInstance) GetFullyQualifiedType() string {
	return "threeport.io/v0.TracingInstance"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (ti *TracingInstance) ScheduledForDeletion() *time.Time {
	return ti.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on TracingInstance.
func (t *TracingInstance) RelationshipTaggedForeignKeys() []RelationshipTaggedForeignKey {
	return []RelationshipTaggedForeignKey{{
		FieldName:    "KubernetesRuntimeInstanceID",
		ObjectID:     t.KubernetesRuntimeInstanceID,
		ObjectType:   new(KubernetesRuntimeInstance).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}, {
		FieldName:    "TempoHelmWorkloadInstanceID",
		ObjectID:     t.TempoHelmWorkloadInstanceID,
		ObjectType:   new(HelmWorkloadInstance).GetFullyQualifiedType(),
		Relationship: RelationshipOwns,
	}, {
		FieldName:    "TracingDefinitionID",
		ObjectID:     t.TracingDefinitionID,
		ObjectType:   new(TracingDefinition).GetFullyQualifiedType(),
		Relationship: RelationshipRequires,
	}}
}
