before:
builds:
  - id: tptctl-darwin-amd64
    binary: tptctl
    main: cmd/tptctl/main.go
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - GCCGO=gccgo
      - AR=ar
      - CC=clang
      - CXX=clang++
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O2 -g
      - CGO_CPPFLAGS=""
      - CGO_CXXFLAGS=-O2 -g
      - CGO_FFLAGS=-O2 -g
      - CGO_LDFLAGS=-O2 -g
      - PKG_CONFIG=pkg-config
      - GOGCCFLAGS=-fPIC -arch amd64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/wm/z_xwbqnn3vq70c82bv3wcdd40000gn/T/go-build4024893129=/tmp/go-build -gno-record-gcc-switches -fno-common
  - id: tptctl-darwin-arm64
    binary: tptctl
    main: cmd/tptctl/main.go
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - GCCGO=gccgo
      - AR=ar
      - CC=clang
      - CXX=clang++
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O2 -g
      - CGO_CPPFLAGS=""
      - CGO_CXXFLAGS=-O2 -g
      - CGO_FFLAGS=-O2 -g
      - CGO_LDFLAGS=-O2 -g
      - PKG_CONFIG=pkg-config
      - GOGCCFLAGS=-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/wm/z_xwbqnn3vq70c82bv3wcdd40000gn/T/go-build4024893129=/tmp/go-build -gno-record-gcc-switches -fno-common
  - id: threeport-sdk
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    main: cmd/sdk/main.go
    binary: threeport-sdk
archives:
  - name_template: 'threeport_v{{ .Version }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "386" }}i386{{ else }}{{ .Arch }}{{ end }}'
    files:
      - README.md
    wrap_in_directory: true
    allow_different_binary_count: true
checksum:
  name_template: 'checksums-darwin.txt'

