// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	"fmt"
	"os"
	"text/tabwriter"

	config_v0 "github.com/threeport/threeport/pkg/config/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// outputGetv0ObservabilityStacksCmd produces the tabular output for the
// 'get observability-stacks' command.
func outputGetv0ObservabilityStacksCmd(
	observabilityStacks *[]config_v0.ObservabilityStackConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "NAME\t OBSERVABILITY STACK DEFINITION\t OBSERVABILITY STACK INSTANCE\t KUBERNETES RUNTIME INSTANCE\t METRICS ENABLED\t METRICS STORAGE ENABLED\t LOGGING ENABLED\t TRACING ENABLED\t INSTRUMENTATION AGENT ENABLED\t INSTRUMENTATION GATEWAY ENABLED\t INSTRUMENTATION BROWSER RELAY ENABLED\t AGE")
	for _, observabilityStack := range *observabilityStacks {
		kubernetesRuntimeInstanceName := ""
		if observabilityStack.ObservabilityStack.KubernetesRuntimeInstance != nil &&
			observabilityStack.ObservabilityStack.KubernetesRuntimeInstance.Name != nil {
			kubernetesRuntimeInstanceName = *observabilityStack.ObservabilityStack.KubernetesRuntimeInstance.Name
		}
		age := ""
		if observabilityStack.ObservabilityStack.Age != nil {
			age = *observabilityStack.ObservabilityStack.Age
		}
		fmt.Fprintln(
			writer,
			*observabilityStack.ObservabilityStack.Name, "\t",
			*observabilityStack.ObservabilityStack.Name, "\t",
			*observabilityStack.ObservabilityStack.Name, "\t",
			kubernetesRuntimeInstanceName, "\t",
			util.Deref(observabilityStack.ObservabilityStack.MetricsEnabled), "\t",
			util.Deref(observabilityStack.ObservabilityStack.MetricsStorageEnabled), "\t",
			util.Deref(observabilityStack.ObservabilityStack.LoggingEnabled), "\t",
			util.Deref(observabilityStack.ObservabilityStack.TracingEnabled), "\t",
			util.Deref(observabilityStack.ObservabilityStack.InstrumentationAgentEnabled), "\t",
			util.Deref(observabilityStack.ObservabilityStack.InstrumentationGatewayEnabled), "\t",
			util.Deref(observabilityStack.ObservabilityStack.InstrumentationBrowserRelayEnabled), "\t",
			age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0ObservabilityStackDefinitionsCmd produces the tabular output for the
// `get observability-stack-definitions` command.
func outputGetv0ObservabilityStackDefinitionsCmd(
	observabilityStackDefinitions *[]config_v0.ObservabilityStackDefinitionConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, observabilityStackDefinition := range *observabilityStackDefinitions {
		age := ""
		if observabilityStackDefinition.ObservabilityStackDefinition.Age != nil {
			age = *observabilityStackDefinition.ObservabilityStackDefinition.Age
		}
		fmt.Fprintln(
			writer,
			*observabilityStackDefinition.ObservabilityStackDefinition.Name, "\t",
			age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0ObservabilityStackInstancesCmd produces the tabular output for the
// `get observability-stack-instances` command.
func outputGetv0ObservabilityStackInstancesCmd(
	observabilityStackInstances *[]config_v0.ObservabilityStackInstanceConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	fmt.Fprintln(writer, "NAME\t OBSERVABILITY STACK DEFINITION\t KUBERNETES RUNTIME INSTANCE\t METRICS ENABLED\t METRICS STORAGE ENABLED\t LOGGING ENABLED\t TRACING ENABLED\t INSTRUMENTATION AGENT ENABLED\t INSTRUMENTATION GATEWAY ENABLED\t INSTRUMENTATION BROWSER RELAY ENABLED\t AGE")
	for _, observabilityStackInstance := range *observabilityStackInstances {
		observabilityStackDefinitionName := ""
		if observabilityStackInstance.ObservabilityStackInstance.ObservabilityStackDefinition != nil &&
			observabilityStackInstance.ObservabilityStackInstance.ObservabilityStackDefinition.Name != nil {
			observabilityStackDefinitionName = *observabilityStackInstance.ObservabilityStackInstance.ObservabilityStackDefinition.Name
		}
		kubernetesRuntimeInstanceName := ""
		if observabilityStackInstance.ObservabilityStackInstance.KubernetesRuntimeInstance != nil &&
			observabilityStackInstance.ObservabilityStackInstance.KubernetesRuntimeInstance.Name != nil {
			kubernetesRuntimeInstanceName = *observabilityStackInstance.ObservabilityStackInstance.KubernetesRuntimeInstance.Name
		}
		age := ""
		if observabilityStackInstance.ObservabilityStackInstance.Age != nil {
			age = *observabilityStackInstance.ObservabilityStackInstance.Age
		}
		fmt.Fprintln(
			writer,
			*observabilityStackInstance.ObservabilityStackInstance.Name, "\t",
			observabilityStackDefinitionName, "\t",
			kubernetesRuntimeInstanceName, "\t",
			util.Deref(observabilityStackInstance.ObservabilityStackInstance.MetricsEnabled), "\t",
			util.Deref(observabilityStackInstance.ObservabilityStackInstance.MetricsStorageEnabled), "\t",
			util.Deref(observabilityStackInstance.ObservabilityStackInstance.LoggingEnabled), "\t",
			util.Deref(observabilityStackInstance.ObservabilityStackInstance.TracingEnabled), "\t",
			util.Deref(observabilityStackInstance.ObservabilityStackInstance.InstrumentationAgentEnabled), "\t",
			util.Deref(observabilityStackInstance.ObservabilityStackInstance.InstrumentationGatewayEnabled), "\t",
			util.Deref(observabilityStackInstance.ObservabilityStackInstance.InstrumentationBrowserRelayEnabled), "\t",
			age,
		)
	}
	writer.Flush()

	return nil
}
