// boilerplate generated by 'threeport-sdk gen' - do not edit

package notif

const (
	ObservabilityStreamName = "observabilityStream"

	ObservabilityStackDefinitionSubject       = "observabilityStackDefinition.*"
	ObservabilityStackDefinitionCreateSubject = "observabilityStackDefinition.create"
	ObservabilityStackDefinitionUpdateSubject = "observabilityStackDefinition.update"
	ObservabilityStackDefinitionDeleteSubject = "observabilityStackDefinition.delete"

	ObservabilityStackInstanceSubject       = "observabilityStackInstance.*"
	ObservabilityStackInstanceCreateSubject = "observabilityStackInstance.create"
	ObservabilityStackInstanceUpdateSubject = "observabilityStackInstance.update"
	ObservabilityStackInstanceDeleteSubject = "observabilityStackInstance.delete"

	ObservabilityDashboardDefinitionSubject       = "observabilityDashboardDefinition.*"
	ObservabilityDashboardDefinitionCreateSubject = "observabilityDashboardDefinition.create"
	ObservabilityDashboardDefinitionUpdateSubject = "observabilityDashboardDefinition.update"
	ObservabilityDashboardDefinitionDeleteSubject = "observabilityDashboardDefinition.delete"

	ObservabilityDashboardInstanceSubject       = "observabilityDashboardInstance.*"
	ObservabilityDashboardInstanceCreateSubject = "observabilityDashboardInstance.create"
	ObservabilityDashboardInstanceUpdateSubject = "observabilityDashboardInstance.update"
	ObservabilityDashboardInstanceDeleteSubject = "observabilityDashboardInstance.delete"

	MetricsDefinitionSubject       = "metricsDefinition.*"
	MetricsDefinitionCreateSubject = "metricsDefinition.create"
	MetricsDefinitionUpdateSubject = "metricsDefinition.update"
	MetricsDefinitionDeleteSubject = "metricsDefinition.delete"

	MetricsInstanceSubject       = "metricsInstance.*"
	MetricsInstanceCreateSubject = "metricsInstance.create"
	MetricsInstanceUpdateSubject = "metricsInstance.update"
	MetricsInstanceDeleteSubject = "metricsInstance.delete"

	LoggingDefinitionSubject       = "loggingDefinition.*"
	LoggingDefinitionCreateSubject = "loggingDefinition.create"
	LoggingDefinitionUpdateSubject = "loggingDefinition.update"
	LoggingDefinitionDeleteSubject = "loggingDefinition.delete"

	LoggingInstanceSubject       = "loggingInstance.*"
	LoggingInstanceCreateSubject = "loggingInstance.create"
	LoggingInstanceUpdateSubject = "loggingInstance.update"
	LoggingInstanceDeleteSubject = "loggingInstance.delete"

	TracingDefinitionSubject       = "tracingDefinition.*"
	TracingDefinitionCreateSubject = "tracingDefinition.create"
	TracingDefinitionUpdateSubject = "tracingDefinition.update"
	TracingDefinitionDeleteSubject = "tracingDefinition.delete"

	TracingInstanceSubject       = "tracingInstance.*"
	TracingInstanceCreateSubject = "tracingInstance.create"
	TracingInstanceUpdateSubject = "tracingInstance.update"
	TracingInstanceDeleteSubject = "tracingInstance.delete"

	InstrumentationAgentDefinitionSubject       = "instrumentationAgentDefinition.*"
	InstrumentationAgentDefinitionCreateSubject = "instrumentationAgentDefinition.create"
	InstrumentationAgentDefinitionUpdateSubject = "instrumentationAgentDefinition.update"
	InstrumentationAgentDefinitionDeleteSubject = "instrumentationAgentDefinition.delete"

	InstrumentationAgentInstanceSubject       = "instrumentationAgentInstance.*"
	InstrumentationAgentInstanceCreateSubject = "instrumentationAgentInstance.create"
	InstrumentationAgentInstanceUpdateSubject = "instrumentationAgentInstance.update"
	InstrumentationAgentInstanceDeleteSubject = "instrumentationAgentInstance.delete"

	InstrumentationGatewayDefinitionSubject       = "instrumentationGatewayDefinition.*"
	InstrumentationGatewayDefinitionCreateSubject = "instrumentationGatewayDefinition.create"
	InstrumentationGatewayDefinitionUpdateSubject = "instrumentationGatewayDefinition.update"
	InstrumentationGatewayDefinitionDeleteSubject = "instrumentationGatewayDefinition.delete"

	InstrumentationGatewayInstanceSubject       = "instrumentationGatewayInstance.*"
	InstrumentationGatewayInstanceCreateSubject = "instrumentationGatewayInstance.create"
	InstrumentationGatewayInstanceUpdateSubject = "instrumentationGatewayInstance.update"
	InstrumentationGatewayInstanceDeleteSubject = "instrumentationGatewayInstance.delete"

	InstrumentationBrowserRelayDefinitionSubject       = "instrumentationBrowserRelayDefinition.*"
	InstrumentationBrowserRelayDefinitionCreateSubject = "instrumentationBrowserRelayDefinition.create"
	InstrumentationBrowserRelayDefinitionUpdateSubject = "instrumentationBrowserRelayDefinition.update"
	InstrumentationBrowserRelayDefinitionDeleteSubject = "instrumentationBrowserRelayDefinition.delete"

	InstrumentationBrowserRelayInstanceSubject       = "instrumentationBrowserRelayInstance.*"
	InstrumentationBrowserRelayInstanceCreateSubject = "instrumentationBrowserRelayInstance.create"
	InstrumentationBrowserRelayInstanceUpdateSubject = "instrumentationBrowserRelayInstance.update"
	InstrumentationBrowserRelayInstanceDeleteSubject = "instrumentationBrowserRelayInstance.delete"
)

// GetObservabilityStackDefinitionSubjects returns the NATS subjects
// for observability stack definitions.
func GetObservabilityStackDefinitionSubjects() []string {
	return []string{
		ObservabilityStackDefinitionCreateSubject,
		ObservabilityStackDefinitionUpdateSubject,
		ObservabilityStackDefinitionDeleteSubject,
	}
}

// GetObservabilityStackInstanceSubjects returns the NATS subjects
// for observability stack instances.
func GetObservabilityStackInstanceSubjects() []string {
	return []string{
		ObservabilityStackInstanceCreateSubject,
		ObservabilityStackInstanceUpdateSubject,
		ObservabilityStackInstanceDeleteSubject,
	}
}

// GetObservabilityDashboardDefinitionSubjects returns the NATS subjects
// for observability dashboard definitions.
func GetObservabilityDashboardDefinitionSubjects() []string {
	return []string{
		ObservabilityDashboardDefinitionCreateSubject,
		ObservabilityDashboardDefinitionUpdateSubject,
		ObservabilityDashboardDefinitionDeleteSubject,
	}
}

// GetObservabilityDashboardInstanceSubjects returns the NATS subjects
// for observability dashboard instances.
func GetObservabilityDashboardInstanceSubjects() []string {
	return []string{
		ObservabilityDashboardInstanceCreateSubject,
		ObservabilityDashboardInstanceUpdateSubject,
		ObservabilityDashboardInstanceDeleteSubject,
	}
}

// GetMetricsDefinitionSubjects returns the NATS subjects
// for metrics definitions.
func GetMetricsDefinitionSubjects() []string {
	return []string{
		MetricsDefinitionCreateSubject,
		MetricsDefinitionUpdateSubject,
		MetricsDefinitionDeleteSubject,
	}
}

// GetMetricsInstanceSubjects returns the NATS subjects
// for metrics instances.
func GetMetricsInstanceSubjects() []string {
	return []string{
		MetricsInstanceCreateSubject,
		MetricsInstanceUpdateSubject,
		MetricsInstanceDeleteSubject,
	}
}

// GetLoggingDefinitionSubjects returns the NATS subjects
// for logging definitions.
func GetLoggingDefinitionSubjects() []string {
	return []string{
		LoggingDefinitionCreateSubject,
		LoggingDefinitionUpdateSubject,
		LoggingDefinitionDeleteSubject,
	}
}

// GetLoggingInstanceSubjects returns the NATS subjects
// for logging instances.
func GetLoggingInstanceSubjects() []string {
	return []string{
		LoggingInstanceCreateSubject,
		LoggingInstanceUpdateSubject,
		LoggingInstanceDeleteSubject,
	}
}

// GetTracingDefinitionSubjects returns the NATS subjects
// for tracing definitions.
func GetTracingDefinitionSubjects() []string {
	return []string{
		TracingDefinitionCreateSubject,
		TracingDefinitionUpdateSubject,
		TracingDefinitionDeleteSubject,
	}
}

// GetTracingInstanceSubjects returns the NATS subjects
// for tracing instances.
func GetTracingInstanceSubjects() []string {
	return []string{
		TracingInstanceCreateSubject,
		TracingInstanceUpdateSubject,
		TracingInstanceDeleteSubject,
	}
}

// GetInstrumentationAgentDefinitionSubjects returns the NATS subjects
// for instrumentation agent definitions.
func GetInstrumentationAgentDefinitionSubjects() []string {
	return []string{
		InstrumentationAgentDefinitionCreateSubject,
		InstrumentationAgentDefinitionUpdateSubject,
		InstrumentationAgentDefinitionDeleteSubject,
	}
}

// GetInstrumentationAgentInstanceSubjects returns the NATS subjects
// for instrumentation agent instances.
func GetInstrumentationAgentInstanceSubjects() []string {
	return []string{
		InstrumentationAgentInstanceCreateSubject,
		InstrumentationAgentInstanceUpdateSubject,
		InstrumentationAgentInstanceDeleteSubject,
	}
}

// GetInstrumentationGatewayDefinitionSubjects returns the NATS subjects
// for instrumentation gateway definitions.
func GetInstrumentationGatewayDefinitionSubjects() []string {
	return []string{
		InstrumentationGatewayDefinitionCreateSubject,
		InstrumentationGatewayDefinitionUpdateSubject,
		InstrumentationGatewayDefinitionDeleteSubject,
	}
}

// GetInstrumentationGatewayInstanceSubjects returns the NATS subjects
// for instrumentation gateway instances.
func GetInstrumentationGatewayInstanceSubjects() []string {
	return []string{
		InstrumentationGatewayInstanceCreateSubject,
		InstrumentationGatewayInstanceUpdateSubject,
		InstrumentationGatewayInstanceDeleteSubject,
	}
}

// GetInstrumentationBrowserRelayDefinitionSubjects returns the NATS subjects
// for instrumentation browser relay definitions.
func GetInstrumentationBrowserRelayDefinitionSubjects() []string {
	return []string{
		InstrumentationBrowserRelayDefinitionCreateSubject,
		InstrumentationBrowserRelayDefinitionUpdateSubject,
		InstrumentationBrowserRelayDefinitionDeleteSubject,
	}
}

// GetInstrumentationBrowserRelayInstanceSubjects returns the NATS subjects
// for instrumentation browser relay instances.
func GetInstrumentationBrowserRelayInstanceSubjects() []string {
	return []string{
		InstrumentationBrowserRelayInstanceCreateSubject,
		InstrumentationBrowserRelayInstanceUpdateSubject,
		InstrumentationBrowserRelayInstanceDeleteSubject,
	}
}

// GetObservabilitySubjects returns the NATS subjects
// for all observability objects.
func GetObservabilitySubjects() []string {
	var observabilitySubjects []string

	observabilitySubjects = append(observabilitySubjects, GetObservabilityStackDefinitionSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetObservabilityStackInstanceSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetObservabilityDashboardDefinitionSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetObservabilityDashboardInstanceSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetMetricsDefinitionSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetMetricsInstanceSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetLoggingDefinitionSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetLoggingInstanceSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetTracingDefinitionSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetTracingInstanceSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetInstrumentationAgentDefinitionSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetInstrumentationAgentInstanceSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetInstrumentationGatewayDefinitionSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetInstrumentationGatewayInstanceSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetInstrumentationBrowserRelayDefinitionSubjects()...)
	observabilitySubjects = append(observabilitySubjects, GetInstrumentationBrowserRelayInstanceSubjects()...)

	return observabilitySubjects
}
