// boilerplate generated by 'threeport-sdk gen' - do not edit

package versions

import (
	apiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	apiserver_v0 "github.com/threeport/threeport/pkg/api-server/v0"
	api_lib "github.com/threeport/threeport/pkg/api/lib/v0"
	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	"reflect"
)

// AddInstrumentationAgentDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddInstrumentationAgentDefinitionVersions() {
	apiserver_v0.InstrumentationAgentDefinitionTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.InstrumentationAgentDefinition)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.InstrumentationAgentDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeInstrumentationAgentDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.InstrumentationAgentDefinitionTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddInstrumentationAgentInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddInstrumentationAgentInstanceVersions() {
	apiserver_v0.InstrumentationAgentInstanceTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.InstrumentationAgentInstance)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.InstrumentationAgentInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeInstrumentationAgentInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.InstrumentationAgentInstanceTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddInstrumentationBrowserRelayDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddInstrumentationBrowserRelayDefinitionVersions() {
	apiserver_v0.InstrumentationBrowserRelayDefinitionTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.InstrumentationBrowserRelayDefinition)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.InstrumentationBrowserRelayDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeInstrumentationBrowserRelayDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.InstrumentationBrowserRelayDefinitionTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddInstrumentationBrowserRelayInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddInstrumentationBrowserRelayInstanceVersions() {
	apiserver_v0.InstrumentationBrowserRelayInstanceTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.InstrumentationBrowserRelayInstance)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.InstrumentationBrowserRelayInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeInstrumentationBrowserRelayInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.InstrumentationBrowserRelayInstanceTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddInstrumentationGatewayDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddInstrumentationGatewayDefinitionVersions() {
	apiserver_v0.InstrumentationGatewayDefinitionTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.InstrumentationGatewayDefinition)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.InstrumentationGatewayDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeInstrumentationGatewayDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.InstrumentationGatewayDefinitionTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddInstrumentationGatewayInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddInstrumentationGatewayInstanceVersions() {
	apiserver_v0.InstrumentationGatewayInstanceTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.InstrumentationGatewayInstance)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.InstrumentationGatewayInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeInstrumentationGatewayInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.InstrumentationGatewayInstanceTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddLoggingDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddLoggingDefinitionVersions() {
	apiserver_v0.LoggingDefinitionTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.LoggingDefinition)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.LoggingDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeLoggingDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.LoggingDefinitionTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddLoggingInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddLoggingInstanceVersions() {
	apiserver_v0.LoggingInstanceTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.LoggingInstance)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.LoggingInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeLoggingInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.LoggingInstanceTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddMetricsDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddMetricsDefinitionVersions() {
	apiserver_v0.MetricsDefinitionTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.MetricsDefinition)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.MetricsDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeMetricsDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.MetricsDefinitionTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddMetricsInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddMetricsInstanceVersions() {
	apiserver_v0.MetricsInstanceTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.MetricsInstance)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.MetricsInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeMetricsInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.MetricsInstanceTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddMetricsStorageDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddMetricsStorageDefinitionVersions() {
	apiserver_v0.MetricsStorageDefinitionTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.MetricsStorageDefinition)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.MetricsStorageDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeMetricsStorageDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.MetricsStorageDefinitionTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddMetricsStorageInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddMetricsStorageInstanceVersions() {
	apiserver_v0.MetricsStorageInstanceTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.MetricsStorageInstance)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.MetricsStorageInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeMetricsStorageInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.MetricsStorageInstanceTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddObservabilityDashboardDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddObservabilityDashboardDefinitionVersions() {
	apiserver_v0.ObservabilityDashboardDefinitionTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.ObservabilityDashboardDefinition)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.ObservabilityDashboardDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeObservabilityDashboardDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.ObservabilityDashboardDefinitionTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddObservabilityDashboardInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddObservabilityDashboardInstanceVersions() {
	apiserver_v0.ObservabilityDashboardInstanceTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.ObservabilityDashboardInstance)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.ObservabilityDashboardInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeObservabilityDashboardInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.ObservabilityDashboardInstanceTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddObservabilityStackDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddObservabilityStackDefinitionVersions() {
	apiserver_v0.ObservabilityStackDefinitionTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.ObservabilityStackDefinition)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.ObservabilityStackDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeObservabilityStackDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.ObservabilityStackDefinitionTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddObservabilityStackInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddObservabilityStackInstanceVersions() {
	apiserver_v0.ObservabilityStackInstanceTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.ObservabilityStackInstance)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.ObservabilityStackInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeObservabilityStackInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.ObservabilityStackInstanceTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddTracingDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddTracingDefinitionVersions() {
	apiserver_v0.TracingDefinitionTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.TracingDefinition)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.TracingDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeTracingDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.TracingDefinitionTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}

// AddTracingInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddTracingInstanceVersions() {
	apiserver_v0.TracingInstanceTaggedFields[string(api_lib.ValidateTag)] = &apiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(api_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	apiserver_lib.ParseStruct(
		string(api_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.TracingInstance)),
		"",
		apiserver_lib.Translate,
		apiserver_v0.TracingInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := apiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeTracingInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	apiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.TracingInstanceTaggedFields[string(api_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	apiserver_lib.AddObjectVersion(versionObj)
}
