// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package observability

import (
	logr "github.com/go-logr/logr"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0InstrumentationBrowserRelayInstanceCreated performs reconciliation when a v0 InstrumentationBrowserRelayInstance
// has been created.
func v0InstrumentationBrowserRelayInstanceCreated(
	r *controller.Reconciler,
	instrumentationBrowserRelayInstance *v0.InstrumentationBrowserRelayInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0InstrumentationBrowserRelayInstanceUpdated performs reconciliation when a v0 InstrumentationBrowserRelayInstance
// has been updated.
func v0InstrumentationBrowserRelayInstanceUpdated(
	r *controller.Reconciler,
	instrumentationBrowserRelayInstance *v0.InstrumentationBrowserRelayInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0InstrumentationBrowserRelayInstanceDeleted performs reconciliation when a v0 InstrumentationBrowserRelayInstance
// has been deleted.
func v0InstrumentationBrowserRelayInstanceDeleted(
	r *controller.Reconciler,
	instrumentationBrowserRelayInstance *v0.InstrumentationBrowserRelayInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
