// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package observability

import (
	logr "github.com/go-logr/logr"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0InstrumentationGatewayInstanceCreated performs reconciliation when a v0 InstrumentationGatewayInstance
// has been created.
func v0InstrumentationGatewayInstanceCreated(
	r *controller.Reconciler,
	instrumentationGatewayInstance *v0.InstrumentationGatewayInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0InstrumentationGatewayInstanceUpdated performs reconciliation when a v0 InstrumentationGatewayInstance
// has been updated.
func v0InstrumentationGatewayInstanceUpdated(
	r *controller.Reconciler,
	instrumentationGatewayInstance *v0.InstrumentationGatewayInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0InstrumentationGatewayInstanceDeleted performs reconciliation when a v0 InstrumentationGatewayInstance
// has been deleted.
func v0InstrumentationGatewayInstanceDeleted(
	r *controller.Reconciler,
	instrumentationGatewayInstance *v0.InstrumentationGatewayInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
