// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package observability

import (
	logr "github.com/go-logr/logr"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0InstrumentationAgentDefinitionCreated performs reconciliation when a v0 InstrumentationAgentDefinition
// has been created.
func v0InstrumentationAgentDefinitionCreated(
	r *controller.Reconciler,
	instrumentationAgentDefinition *v0.InstrumentationAgentDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0InstrumentationAgentDefinitionUpdated performs reconciliation when a v0 InstrumentationAgentDefinition
// has been updated.
func v0InstrumentationAgentDefinitionUpdated(
	r *controller.Reconciler,
	instrumentationAgentDefinition *v0.InstrumentationAgentDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0InstrumentationAgentDefinitionDeleted performs reconciliation when a v0 InstrumentationAgentDefinition
// has been deleted.
func v0InstrumentationAgentDefinitionDeleted(
	r *controller.Reconciler,
	instrumentationAgentDefinition *v0.InstrumentationAgentDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
