// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package observability

import (
	logr "github.com/go-logr/logr"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0InstrumentationGatewayDefinitionCreated performs reconciliation when a v0 InstrumentationGatewayDefinition
// has been created.
func v0InstrumentationGatewayDefinitionCreated(
	r *controller.Reconciler,
	instrumentationGatewayDefinition *v0.InstrumentationGatewayDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0InstrumentationGatewayDefinitionUpdated performs reconciliation when a v0 InstrumentationGatewayDefinition
// has been updated.
func v0InstrumentationGatewayDefinitionUpdated(
	r *controller.Reconciler,
	instrumentationGatewayDefinition *v0.InstrumentationGatewayDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0InstrumentationGatewayDefinitionDeleted performs reconciliation when a v0 InstrumentationGatewayDefinition
// has been deleted.
func v0InstrumentationGatewayDefinitionDeleted(
	r *controller.Reconciler,
	instrumentationGatewayDefinition *v0.InstrumentationGatewayDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
