// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package observability

import (
	logr "github.com/go-logr/logr"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0InstrumentationAgentInstanceCreated performs reconciliation when a v0 InstrumentationAgentInstance
// has been created.
func v0InstrumentationAgentInstanceCreated(
	r *controller.Reconciler,
	instrumentationAgentInstance *v0.InstrumentationAgentInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0InstrumentationAgentInstanceUpdated performs reconciliation when a v0 InstrumentationAgentInstance
// has been updated.
func v0InstrumentationAgentInstanceUpdated(
	r *controller.Reconciler,
	instrumentationAgentInstance *v0.InstrumentationAgentInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0InstrumentationAgentInstanceDeleted performs reconciliation when a v0 InstrumentationAgentInstance
// has been deleted.
func v0InstrumentationAgentInstanceDeleted(
	r *controller.Reconciler,
	instrumentationAgentInstance *v0.InstrumentationAgentInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
