// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package observability

import (
	logr "github.com/go-logr/logr"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0InstrumentationBrowserRelayDefinitionCreated performs reconciliation when a v0 InstrumentationBrowserRelayDefinition
// has been created.
func v0InstrumentationBrowserRelayDefinitionCreated(
	r *controller.Reconciler,
	instrumentationBrowserRelayDefinition *v0.InstrumentationBrowserRelayDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0InstrumentationBrowserRelayDefinitionUpdated performs reconciliation when a v0 InstrumentationBrowserRelayDefinition
// has been updated.
func v0InstrumentationBrowserRelayDefinitionUpdated(
	r *controller.Reconciler,
	instrumentationBrowserRelayDefinition *v0.InstrumentationBrowserRelayDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0InstrumentationBrowserRelayDefinitionDeleted performs reconciliation when a v0 InstrumentationBrowserRelayDefinition
// has been deleted.
func v0InstrumentationBrowserRelayDefinitionDeleted(
	r *controller.Reconciler,
	instrumentationBrowserRelayDefinition *v0.InstrumentationBrowserRelayDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
