// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package observability

import (
	logr "github.com/go-logr/logr"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0MetricsStorageInstanceCreated performs reconciliation when a v0 MetricsStorageInstance
// has been created.
func v0MetricsStorageInstanceCreated(
	r *controller.Reconciler,
	metricsStorageInstance *v0.MetricsStorageInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0MetricsStorageInstanceUpdated performs reconciliation when a v0 MetricsStorageInstance
// has been updated.
func v0MetricsStorageInstanceUpdated(
	r *controller.Reconciler,
	metricsStorageInstance *v0.MetricsStorageInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0MetricsStorageInstanceDeleted performs reconciliation when a v0 MetricsStorageInstance
// has been deleted.
func v0MetricsStorageInstanceDeleted(
	r *controller.Reconciler,
	metricsStorageInstance *v0.MetricsStorageInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
