// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package observability

import (
	logr "github.com/go-logr/logr"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0MetricsStorageDefinitionCreated performs reconciliation when a v0 MetricsStorageDefinition
// has been created.
func v0MetricsStorageDefinitionCreated(
	r *controller.Reconciler,
	metricsStorageDefinition *v0.MetricsStorageDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0MetricsStorageDefinitionUpdated performs reconciliation when a v0 MetricsStorageDefinition
// has been updated.
func v0MetricsStorageDefinitionUpdated(
	r *controller.Reconciler,
	metricsStorageDefinition *v0.MetricsStorageDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0MetricsStorageDefinitionDeleted performs reconciliation when a v0 MetricsStorageDefinition
// has been deleted.
func v0MetricsStorageDefinitionDeleted(
	r *controller.Reconciler,
	metricsStorageDefinition *v0.MetricsStorageDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
