// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package observability

import (
	logr "github.com/go-logr/logr"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0TracingInstanceCreated performs reconciliation when a v0 TracingInstance
// has been created.
func v0TracingInstanceCreated(
	r *controller.Reconciler,
	tracingInstance *v0.TracingInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0TracingInstanceUpdated performs reconciliation when a v0 TracingInstance
// has been updated.
func v0TracingInstanceUpdated(
	r *controller.Reconciler,
	tracingInstance *v0.TracingInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0TracingInstanceDeleted performs reconciliation when a v0 TracingInstance
// has been deleted.
func v0TracingInstanceDeleted(
	r *controller.Reconciler,
	tracingInstance *v0.TracingInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
