// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package observability

import (
	logr "github.com/go-logr/logr"
	v0 "github.com/threeport/threeport/pkg/api/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0TracingDefinitionCreated performs reconciliation when a v0 TracingDefinition
// has been created.
func v0TracingDefinitionCreated(
	r *controller.Reconciler,
	tracingDefinition *v0.TracingDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0TracingDefinitionUpdated performs reconciliation when a v0 TracingDefinition
// has been updated.
func v0TracingDefinitionUpdated(
	r *controller.Reconciler,
	tracingDefinition *v0.TracingDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0TracingDefinitionDeleted performs reconciliation when a v0 TracingDefinition
// has been deleted.
func v0TracingDefinitionDeleted(
	r *controller.Reconciler,
	tracingDefinition *v0.TracingDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
