name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  goreleaser-darwin:
    runs-on: macos-15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Check go version
      run: go version

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5.0.0
      with:
        version: v1.26.2
        args: release --clean -f ./.goreleaser-darwin.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check pflag version
      run: go list -m -json all | jq -r 'select(.Path == "github.com/spf13/pflag") | .Version'

  goreleaser:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf libc6-dev-arm64-cross libc6-dev-armhf-cross g++-aarch64-linux-gnu clang

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_ACCESS_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5.0.0
      with:
        version: v1.26.2
        args: release --clean -f ./.goreleaser.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

