// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"errors"
	"fmt"
	"net/http"

	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	client_v0 "github.com/threeport/threeport/pkg/client/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// ObservabilityStackInstanceConfig is a config abstraction for the ObservabilityStackInstance API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type ObservabilityStackInstanceConfig struct {
	ObservabilityStackInstance ObservabilityStackInstanceValues
}

// ObservabilityStackInstanceValues contains all the attributes needed to manage
// the ObservabilityStackInstance API object.
type ObservabilityStackInstanceValues struct {
	Name                                  *string                             `json:",omitempty"`
	KubernetesRuntimeInstance             *KubernetesRuntimeInstanceValues    `json:",omitempty"`
	MetricsEnabled                        *bool                               `json:",omitempty"`
	MetricsStorageEnabled                 *bool                               `json:",omitempty"`
	LoggingEnabled                        *bool                               `json:",omitempty"`
	TracingEnabled                        *bool                               `json:",omitempty"`
	InstrumentationAgentEnabled           *bool                               `json:",omitempty"`
	InstrumentationGatewayEnabled         *bool                               `json:",omitempty"`
	InstrumentationBrowserRelayEnabled    *bool                               `json:",omitempty"`
	GrafanaHelmValues                     *string                             `json:",omitempty"`
	GrafanaHelmValuesDocument             *string                             `json:",omitempty"`
	KubePrometheusStackHelmValues         *string                             `json:",omitempty"`
	KubePrometheusStackHelmValuesDocument *string                             `json:",omitempty"`
	MimirHelmValues                       *string                             `json:",omitempty"`
	MimirHelmValuesDocument               *string                             `json:",omitempty"`
	LokiHelmValues                        *string                             `json:",omitempty"`
	LokiHelmValuesDocument                *string                             `json:",omitempty"`
	TempoHelmValues                       *string                             `json:",omitempty"`
	TempoHelmValuesDocument               *string                             `json:",omitempty"`
	OtelAgentHelmValues                   *string                             `json:",omitempty"`
	OtelAgentHelmValuesDocument           *string                             `json:",omitempty"`
	OtelGatewayHelmValues                 *string                             `json:",omitempty"`
	OtelGatewayHelmValuesDocument         *string                             `json:",omitempty"`
	OtelBrowserRelayHelmValues            *string                             `json:",omitempty"`
	OtelBrowserRelayHelmValuesDocument    *string                             `json:",omitempty"`
	ObservabilityConfigPath               *string                             `json:",omitempty"`
	ObservabilityStackDefinition          *ObservabilityStackDefinitionValues `json:",omitempty"`
	Age                                   *string                             `json:",omitempty"`
}

// Get gets observability stack instances from the Threeport API.
// If the name is set in the ObservabilityStackInstanceValues, it will return the observability stack instance with that name.
// If the name is not set, it will return all observability stack instances.
func (o *ObservabilityStackInstanceConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]ObservabilityStackInstanceConfig, error) {
	observabilityStackInstanceValues := o.ObservabilityStackInstance
	// get API objects
	var observabilityStackInstances *[]api_v0.ObservabilityStackInstance
	switch {
	// if name is provided, get observability stack instance by name
	case observabilityStackInstanceValues.Name != nil:
		observabilityStackInstance, err := client_v0.GetObservabilityStackInstanceByName(apiClient, apiEndpoint, *observabilityStackInstanceValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get observability stack instance with name %s: %w", *observabilityStackInstanceValues.Name, err)
		}
		observabilityStackInstances = &[]api_v0.ObservabilityStackInstance{*observabilityStackInstance}
	// get all observability stack instances
	default:
		allObservabilityStackInstances, err := client_v0.GetObservabilityStackInstances(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get observability stack instances from Threeport API: %w", err)
		}
		observabilityStackInstances = allObservabilityStackInstances
	}

	// assemble config objects from API objects
	var observabilityStackInstanceConfigs []ObservabilityStackInstanceConfig
	for _, observabilityStackInstance := range *observabilityStackInstances {
		// related objects
		var kubernetesRuntimeInstance *KubernetesRuntimeInstanceValues
		var observabilityStackDefinition *ObservabilityStackDefinitionValues

		// get kubernetes runtime instance
		if observabilityStackInstance.KubernetesRuntimeInstanceID != nil {
			kri, err := client_v0.GetKubernetesRuntimeInstanceByID(
				apiClient,
				apiEndpoint,
				*observabilityStackInstance.KubernetesRuntimeInstanceID,
			)
			if err == nil {
				kubernetesRuntimeInstance = &KubernetesRuntimeInstanceValues{
					Name: kri.Name,
				}
			}
		}

		// get observability stack definition
		if observabilityStackInstance.ObservabilityStackDefinitionID != nil {
			osd, err := client_v0.GetObservabilityStackDefinitionByID(apiClient, apiEndpoint, *observabilityStackInstance.ObservabilityStackDefinitionID)
			if err == nil {
				observabilityStackDefinition = &ObservabilityStackDefinitionValues{
					Name: osd.Name,
				}
			}
		}

		observabilityStackInstanceConfig := ObservabilityStackInstanceConfig{
			ObservabilityStackInstance: ObservabilityStackInstanceValues{
				Name:                                  observabilityStackInstance.Name,
				KubernetesRuntimeInstance:             kubernetesRuntimeInstance,
				MetricsEnabled:                        observabilityStackInstance.MetricsEnabled,
				MetricsStorageEnabled:                 observabilityStackInstance.MetricsStorageEnabled,
				LoggingEnabled:                        observabilityStackInstance.LoggingEnabled,
				TracingEnabled:                        observabilityStackInstance.TracingEnabled,
				InstrumentationAgentEnabled:           observabilityStackInstance.InstrumentationAgentEnabled,
				InstrumentationGatewayEnabled:         observabilityStackInstance.InstrumentationGatewayEnabled,
				InstrumentationBrowserRelayEnabled:    observabilityStackInstance.InstrumentationBrowserRelayEnabled,
				GrafanaHelmValuesDocument:             observabilityStackInstance.GrafanaHelmValuesDocument,
				KubePrometheusStackHelmValuesDocument: observabilityStackInstance.KubePrometheusStackHelmValuesDocument,
				MimirHelmValuesDocument:               observabilityStackInstance.MimirHelmValuesDocument,
				LokiHelmValuesDocument:                observabilityStackInstance.LokiHelmValuesDocument,
				TempoHelmValuesDocument:               observabilityStackInstance.TempoHelmValuesDocument,
				OtelAgentHelmValuesDocument:           observabilityStackInstance.OtelAgentHelmValuesDocument,
				OtelGatewayHelmValuesDocument:         observabilityStackInstance.OtelGatewayHelmValuesDocument,
				OtelBrowserRelayHelmValuesDocument:    observabilityStackInstance.OtelBrowserRelayHelmValuesDocument,
				ObservabilityStackDefinition:          observabilityStackDefinition,
				Age:                                   util.Ptr(util.GetAgeFormatted(observabilityStackInstance.CreatedAt)),
			},
		}
		observabilityStackInstanceConfigs = append(observabilityStackInstanceConfigs, observabilityStackInstanceConfig)
	}

	return &observabilityStackInstanceConfigs, nil
}

// Create creates a observability stack instance in the Threeport API.
func (o *ObservabilityStackInstanceConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*ObservabilityStackInstanceConfig, error) {
	observabilityStackInstanceValues := o.ObservabilityStackInstance
	// validate config
	if err := o.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for observability stack instance with name %s: %w", *observabilityStackInstanceValues.Name, err)
	}

	// get kubernetes runtime instance
	kubernetesRuntimeInstance, err := getKubernetesRuntimeInstanceByNameOrDefault(
		apiClient,
		apiEndpoint,
		observabilityStackInstanceValues.KubernetesRuntimeInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes runtime instance: %w", err)
	}

	// get observability stack definition
	osd, err := client_v0.GetObservabilityStackDefinitionByName(
		apiClient,
		apiEndpoint,
		*observabilityStackInstanceValues.ObservabilityStackDefinition.Name,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to get observability stack definition by name %s: %w",
			*observabilityStackInstanceValues.ObservabilityStackDefinition.Name,
			err,
		)
	}

	// construct observability stack instance object
	observabilityStackInstance := &api_v0.ObservabilityStackInstance{
		Instance: api_v0.Instance{
			Name: observabilityStackInstanceValues.Name,
		},
		ObservabilityStackDefinitionID:     osd.ID,
		KubernetesRuntimeInstanceID:        kubernetesRuntimeInstance.ID,
		MetricsEnabled:                     observabilityStackInstanceValues.MetricsEnabled,
		MetricsStorageEnabled:              observabilityStackInstanceValues.MetricsStorageEnabled,
		LoggingEnabled:                     observabilityStackInstanceValues.LoggingEnabled,
		TracingEnabled:                     observabilityStackInstanceValues.TracingEnabled,
		InstrumentationAgentEnabled:        observabilityStackInstanceValues.InstrumentationAgentEnabled,
		InstrumentationGatewayEnabled:      observabilityStackInstanceValues.InstrumentationGatewayEnabled,
		InstrumentationBrowserRelayEnabled: observabilityStackInstanceValues.InstrumentationBrowserRelayEnabled,
	}

	// set grafana helm values if present
	grafanaHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.GrafanaHelmValues,
		observabilityStackInstanceValues.GrafanaHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get grafana values document from path: %w", err)
	}
	observabilityStackInstance.GrafanaHelmValuesDocument = grafanaHelmValuesDocument

	// set kube-prometheus-stack helm values if present
	kubePrometheusStackHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.KubePrometheusStackHelmValues,
		observabilityStackInstanceValues.KubePrometheusStackHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kube-prometheus-stack values document from path: %w", err)
	}
	observabilityStackInstance.KubePrometheusStackHelmValuesDocument = kubePrometheusStackHelmValuesDocument

	// set mimir helm values if present
	mimirHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.MimirHelmValues,
		observabilityStackInstanceValues.MimirHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get mimir values document from path: %w", err)
	}
	observabilityStackInstance.MimirHelmValuesDocument = mimirHelmValuesDocument

	// set loki helm values if present
	lokiHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.LokiHelmValues,
		observabilityStackInstanceValues.LokiHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get loki values document from path: %w", err)
	}
	observabilityStackInstance.LokiHelmValuesDocument = lokiHelmValuesDocument

	// set tempo helm values if present
	tempoHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.TempoHelmValues,
		observabilityStackInstanceValues.TempoHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get tempo values document from path: %w", err)
	}
	observabilityStackInstance.TempoHelmValuesDocument = tempoHelmValuesDocument

	// set otel agent helm values if present
	otelAgentHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.OtelAgentHelmValues,
		observabilityStackInstanceValues.OtelAgentHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get otel agent values document from path: %w", err)
	}
	observabilityStackInstance.OtelAgentHelmValuesDocument = otelAgentHelmValuesDocument

	// set otel gateway helm values if present
	otelGatewayHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.OtelGatewayHelmValues,
		observabilityStackInstanceValues.OtelGatewayHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get otel gateway values document from path: %w", err)
	}
	observabilityStackInstance.OtelGatewayHelmValuesDocument = otelGatewayHelmValuesDocument

	// set otel browser relay helm values if present
	otelBrowserRelayHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.OtelBrowserRelayHelmValues,
		observabilityStackInstanceValues.OtelBrowserRelayHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get otel browser relay values document from path: %w", err)
	}
	observabilityStackInstance.OtelBrowserRelayHelmValuesDocument = otelBrowserRelayHelmValuesDocument

	// create observability stack instance
	createdObservabilityStackInstance, err := client_v0.CreateObservabilityStackInstance(
		apiClient,
		apiEndpoint,
		observabilityStackInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create observability stack instance in threeport API: %w", err)
	}

	// construct observability stack instance config
	createdObservabilityStackInstanceConfig := &ObservabilityStackInstanceConfig{
		ObservabilityStackInstance: ObservabilityStackInstanceValues{
			Age:                                   util.Ptr(util.GetAgeFormatted(createdObservabilityStackInstance.CreatedAt)),
			Name:                                  createdObservabilityStackInstance.Name,
			MetricsEnabled:                        createdObservabilityStackInstance.MetricsEnabled,
			MetricsStorageEnabled:                 createdObservabilityStackInstance.MetricsStorageEnabled,
			LoggingEnabled:                        createdObservabilityStackInstance.LoggingEnabled,
			TracingEnabled:                        createdObservabilityStackInstance.TracingEnabled,
			InstrumentationAgentEnabled:           createdObservabilityStackInstance.InstrumentationAgentEnabled,
			InstrumentationGatewayEnabled:         createdObservabilityStackInstance.InstrumentationGatewayEnabled,
			InstrumentationBrowserRelayEnabled:    createdObservabilityStackInstance.InstrumentationBrowserRelayEnabled,
			GrafanaHelmValues:                     observabilityStackInstanceValues.GrafanaHelmValues,
			GrafanaHelmValuesDocument:             createdObservabilityStackInstance.GrafanaHelmValuesDocument,
			KubePrometheusStackHelmValues:         observabilityStackInstanceValues.KubePrometheusStackHelmValues,
			KubePrometheusStackHelmValuesDocument: createdObservabilityStackInstance.KubePrometheusStackHelmValuesDocument,
			MimirHelmValues:                       observabilityStackInstanceValues.MimirHelmValues,
			MimirHelmValuesDocument:               createdObservabilityStackInstance.MimirHelmValuesDocument,
			LokiHelmValues:                        observabilityStackInstanceValues.LokiHelmValues,
			LokiHelmValuesDocument:                createdObservabilityStackInstance.LokiHelmValuesDocument,
			TempoHelmValues:                       observabilityStackInstanceValues.TempoHelmValues,
			TempoHelmValuesDocument:               createdObservabilityStackInstance.TempoHelmValuesDocument,
			OtelAgentHelmValues:                   observabilityStackInstanceValues.OtelAgentHelmValues,
			OtelAgentHelmValuesDocument:           createdObservabilityStackInstance.OtelAgentHelmValuesDocument,
			OtelGatewayHelmValues:                 observabilityStackInstanceValues.OtelGatewayHelmValues,
			OtelGatewayHelmValuesDocument:         createdObservabilityStackInstance.OtelGatewayHelmValuesDocument,
			OtelBrowserRelayHelmValues:            observabilityStackInstanceValues.OtelBrowserRelayHelmValues,
			OtelBrowserRelayHelmValuesDocument:    createdObservabilityStackInstance.OtelBrowserRelayHelmValuesDocument,
			ObservabilityConfigPath:               observabilityStackInstanceValues.ObservabilityConfigPath,
		},
	}

	return createdObservabilityStackInstanceConfig, nil
}

// Replace updates the entire observability stack instance object in the Threeport API.
// This is a full replacement of all fields in the observability stack instance object.
// This function takes a name parameter to identify the observability stack instance to replace.
// This allows a different name to be provided in the values object for name changes.
func (o *ObservabilityStackInstanceConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*ObservabilityStackInstanceConfig, error) {
	observabilityStackInstanceValues := o.ObservabilityStackInstance
	// validate config
	if err := o.Validate(); err != nil {
		return nil, fmt.Errorf("invalid observability stack instance config: %w", err)
	}

	// get existing observability stack instance by name
	existingObservabilityStackInstance, err := client_v0.GetObservabilityStackInstanceByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find observability stack instance with name %s: %w", name, err)
	}

	// ensure user is not trying to move the observability stack to a different runtime
	kubernetesRuntimeInstance, moved, err := getKubernetesRuntimeInstanceAndCheckId(
		apiClient,
		apiEndpoint,
		observabilityStackInstanceValues.KubernetesRuntimeInstance,
		existingObservabilityStackInstance.KubernetesRuntimeInstanceID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes runtime instance: %w", err)
	}
	if moved {
		return nil, fmt.Errorf(
			"an observability stack may not be moved from its current runtime to %s - if %[1]s runtime needs an observability stack, create a new one there instead",
			*kubernetesRuntimeInstance.Name,
		)
	}

	// get observability stack definition
	osd, err := client_v0.GetObservabilityStackDefinitionByName(
		apiClient,
		apiEndpoint,
		*observabilityStackInstanceValues.ObservabilityStackDefinition.Name,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to get observability stack definition by name %s: %w",
			*observabilityStackInstanceValues.ObservabilityStackDefinition.Name,
			err,
		)
	}

	// construct updated observability stack instance object
	updatedObservabilityStackInstance := &api_v0.ObservabilityStackInstance{
		Common: api_v0.Common{
			ID: existingObservabilityStackInstance.ID,
		},
		Instance: api_v0.Instance{
			Name: observabilityStackInstanceValues.Name,
		},
		ObservabilityStackDefinitionID:     osd.ID,
		KubernetesRuntimeInstanceID:        kubernetesRuntimeInstance.ID,
		MetricsEnabled:                     observabilityStackInstanceValues.MetricsEnabled,
		MetricsStorageEnabled:              observabilityStackInstanceValues.MetricsStorageEnabled,
		LoggingEnabled:                     observabilityStackInstanceValues.LoggingEnabled,
		TracingEnabled:                     observabilityStackInstanceValues.TracingEnabled,
		InstrumentationAgentEnabled:        observabilityStackInstanceValues.InstrumentationAgentEnabled,
		InstrumentationGatewayEnabled:      observabilityStackInstanceValues.InstrumentationGatewayEnabled,
		InstrumentationBrowserRelayEnabled: observabilityStackInstanceValues.InstrumentationBrowserRelayEnabled,
	}

	// set grafana helm values if present
	grafanaHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.GrafanaHelmValues,
		observabilityStackInstanceValues.GrafanaHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get grafana values document from path: %w", err)
	}
	updatedObservabilityStackInstance.GrafanaHelmValuesDocument = grafanaHelmValuesDocument

	// set kube-prometheus-stack helm values if present
	kubePrometheusStackHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.KubePrometheusStackHelmValues,
		observabilityStackInstanceValues.KubePrometheusStackHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kube-prometheus-stack values document from path: %w", err)
	}
	updatedObservabilityStackInstance.KubePrometheusStackHelmValuesDocument = kubePrometheusStackHelmValuesDocument

	// set mimir helm values if present
	mimirHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.MimirHelmValues,
		observabilityStackInstanceValues.MimirHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get mimir values document from path: %w", err)
	}
	updatedObservabilityStackInstance.MimirHelmValuesDocument = mimirHelmValuesDocument

	// set loki helm values if present
	lokiHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.LokiHelmValues,
		observabilityStackInstanceValues.LokiHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get loki values document from path: %w", err)
	}
	updatedObservabilityStackInstance.LokiHelmValuesDocument = lokiHelmValuesDocument

	// set tempo helm values if present
	tempoHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.TempoHelmValues,
		observabilityStackInstanceValues.TempoHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get tempo values document from path: %w", err)
	}
	updatedObservabilityStackInstance.TempoHelmValuesDocument = tempoHelmValuesDocument

	// set otel agent helm values if present
	otelAgentHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.OtelAgentHelmValues,
		observabilityStackInstanceValues.OtelAgentHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get otel agent values document from path: %w", err)
	}
	updatedObservabilityStackInstance.OtelAgentHelmValuesDocument = otelAgentHelmValuesDocument

	// set otel gateway helm values if present
	otelGatewayHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.OtelGatewayHelmValues,
		observabilityStackInstanceValues.OtelGatewayHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get otel gateway values document from path: %w", err)
	}
	updatedObservabilityStackInstance.OtelGatewayHelmValuesDocument = otelGatewayHelmValuesDocument

	// set otel browser relay helm values if present
	otelBrowserRelayHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackInstanceValues.OtelBrowserRelayHelmValues,
		observabilityStackInstanceValues.OtelBrowserRelayHelmValuesDocument,
		observabilityStackInstanceValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get otel browser relay values document from path: %w", err)
	}
	updatedObservabilityStackInstance.OtelBrowserRelayHelmValuesDocument = otelBrowserRelayHelmValuesDocument

	// replace observability stack instance
	replacedObservabilityStackInstance, err := client_v0.ReplaceObservabilityStackInstance(
		apiClient,
		apiEndpoint,
		updatedObservabilityStackInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace observability stack instance in threeport API: %w", err)
	}

	// construct updated observability stack instance config
	updatedObservabilityStackInstanceConfig := &ObservabilityStackInstanceConfig{
		ObservabilityStackInstance: ObservabilityStackInstanceValues{
			Age:                                   util.Ptr(util.GetAgeFormatted(replacedObservabilityStackInstance.CreatedAt)),
			Name:                                  replacedObservabilityStackInstance.Name,
			MetricsEnabled:                        replacedObservabilityStackInstance.MetricsEnabled,
			MetricsStorageEnabled:                 replacedObservabilityStackInstance.MetricsStorageEnabled,
			LoggingEnabled:                        replacedObservabilityStackInstance.LoggingEnabled,
			TracingEnabled:                        replacedObservabilityStackInstance.TracingEnabled,
			InstrumentationAgentEnabled:           replacedObservabilityStackInstance.InstrumentationAgentEnabled,
			InstrumentationGatewayEnabled:         replacedObservabilityStackInstance.InstrumentationGatewayEnabled,
			InstrumentationBrowserRelayEnabled:    replacedObservabilityStackInstance.InstrumentationBrowserRelayEnabled,
			GrafanaHelmValues:                     observabilityStackInstanceValues.GrafanaHelmValues,
			GrafanaHelmValuesDocument:             replacedObservabilityStackInstance.GrafanaHelmValuesDocument,
			KubePrometheusStackHelmValues:         observabilityStackInstanceValues.KubePrometheusStackHelmValues,
			KubePrometheusStackHelmValuesDocument: replacedObservabilityStackInstance.KubePrometheusStackHelmValuesDocument,
			MimirHelmValues:                       observabilityStackInstanceValues.MimirHelmValues,
			MimirHelmValuesDocument:               replacedObservabilityStackInstance.MimirHelmValuesDocument,
			LokiHelmValues:                        observabilityStackInstanceValues.LokiHelmValues,
			LokiHelmValuesDocument:                replacedObservabilityStackInstance.LokiHelmValuesDocument,
			TempoHelmValues:                       observabilityStackInstanceValues.TempoHelmValues,
			TempoHelmValuesDocument:               replacedObservabilityStackInstance.TempoHelmValuesDocument,
			OtelAgentHelmValues:                   observabilityStackInstanceValues.OtelAgentHelmValues,
			OtelAgentHelmValuesDocument:           replacedObservabilityStackInstance.OtelAgentHelmValuesDocument,
			OtelGatewayHelmValues:                 observabilityStackInstanceValues.OtelGatewayHelmValues,
			OtelGatewayHelmValuesDocument:         replacedObservabilityStackInstance.OtelGatewayHelmValuesDocument,
			OtelBrowserRelayHelmValues:            observabilityStackInstanceValues.OtelBrowserRelayHelmValues,
			OtelBrowserRelayHelmValuesDocument:    replacedObservabilityStackInstance.OtelBrowserRelayHelmValuesDocument,
			ObservabilityConfigPath:               observabilityStackInstanceValues.ObservabilityConfigPath,
		},
	}

	return updatedObservabilityStackInstanceConfig, nil
}

// Delete deletes a observability stack instance from the Threeport API.
func (o *ObservabilityStackInstanceConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*ObservabilityStackInstanceConfig, error) {
	observabilityStackInstanceValues := o.ObservabilityStackInstance
	// get observability stack instance by name
	observabilityStackInstance, err := client_v0.GetObservabilityStackInstanceByName(
		apiClient,
		apiEndpoint,
		*observabilityStackInstanceValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find observability stack instance with name %s: %w", *observabilityStackInstanceValues.Name, err)
	}

	// delete observability stack instance
	deletedObservabilityStackInstance, err := client_v0.DeleteObservabilityStackInstance(
		apiClient,
		apiEndpoint,
		*observabilityStackInstance.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete observability stack instance from Threeport API: %w", err)
	}

	// wait for observability stack instance to be deleted
	util.Retry(60, 1, func() error {
		if _, err := client_v0.GetObservabilityStackInstanceByName(
			apiClient,
			apiEndpoint,
			*deletedObservabilityStackInstance.Name,
		); err == nil {
			return fmt.Errorf(
				"observability stack instance %s still exists",
				*deletedObservabilityStackInstance.Name,
			)
		}
		return nil
	})

	// construct deleted observability stack instance config
	deletedObservabilityStackInstanceConfig := &ObservabilityStackInstanceConfig{
		ObservabilityStackInstance: ObservabilityStackInstanceValues{
			Name:                                  deletedObservabilityStackInstance.Name,
			MetricsEnabled:                        deletedObservabilityStackInstance.MetricsEnabled,
			MetricsStorageEnabled:                 deletedObservabilityStackInstance.MetricsStorageEnabled,
			LoggingEnabled:                        deletedObservabilityStackInstance.LoggingEnabled,
			TracingEnabled:                        deletedObservabilityStackInstance.TracingEnabled,
			InstrumentationAgentEnabled:           deletedObservabilityStackInstance.InstrumentationAgentEnabled,
			InstrumentationGatewayEnabled:         deletedObservabilityStackInstance.InstrumentationGatewayEnabled,
			InstrumentationBrowserRelayEnabled:    deletedObservabilityStackInstance.InstrumentationBrowserRelayEnabled,
			GrafanaHelmValuesDocument:             deletedObservabilityStackInstance.GrafanaHelmValuesDocument,
			KubePrometheusStackHelmValuesDocument: deletedObservabilityStackInstance.KubePrometheusStackHelmValuesDocument,
			MimirHelmValuesDocument:               deletedObservabilityStackInstance.MimirHelmValuesDocument,
			LokiHelmValuesDocument:                deletedObservabilityStackInstance.LokiHelmValuesDocument,
			TempoHelmValuesDocument:               deletedObservabilityStackInstance.TempoHelmValuesDocument,
			OtelAgentHelmValuesDocument:           deletedObservabilityStackInstance.OtelAgentHelmValuesDocument,
			OtelGatewayHelmValuesDocument:         deletedObservabilityStackInstance.OtelGatewayHelmValuesDocument,
			OtelBrowserRelayHelmValuesDocument:    deletedObservabilityStackInstance.OtelBrowserRelayHelmValuesDocument,
		},
	}

	return deletedObservabilityStackInstanceConfig, nil
}

// Validate validates inputs to create observability stack instances.
func (o *ObservabilityStackInstanceConfig) Validate() error {
	observabilityStackInstanceValues := o.ObservabilityStackInstance
	multiError := util.MultiError{}

	// ensure name is set
	if observabilityStackInstanceValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// ensure observability stack definition is set
	if observabilityStackInstanceValues.ObservabilityStackDefinition == nil {
		multiError.AppendError(fmt.Errorf("ObservabilityStackDefinition is required"))
	}

	// ensure observability stack definition name is set
	if observabilityStackInstanceValues.ObservabilityStackDefinition != nil && observabilityStackInstanceValues.ObservabilityStackDefinition.Name == nil {
		multiError.AppendError(fmt.Errorf("ObservabilityStackDefinition.Name is required"))
	}

	// ensure grafana helm values and document are not both set
	if observabilityStackInstanceValues.GrafanaHelmValues != nil && observabilityStackInstanceValues.GrafanaHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("GrafanaHelmValues and GrafanaHelmValuesDocument cannot both be set"))
	}

	// ensure kube-prometheus-stack helm values and document are not both set
	if observabilityStackInstanceValues.KubePrometheusStackHelmValues != nil && observabilityStackInstanceValues.KubePrometheusStackHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("KubePrometheusStackHelmValues and KubePrometheusStackHelmValuesDocument cannot both be set"))
	}

	// ensure mimir helm values and document are not both set
	if observabilityStackInstanceValues.MimirHelmValues != nil && observabilityStackInstanceValues.MimirHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("MimirHelmValues and MimirHelmValuesDocument cannot both be set"))
	}

	// ensure loki helm values and document are not both set
	if observabilityStackInstanceValues.LokiHelmValues != nil && observabilityStackInstanceValues.LokiHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("LokiHelmValues and LokiHelmValuesDocument cannot both be set"))
	}

	// ensure tempo helm values and document are not both set
	if observabilityStackInstanceValues.TempoHelmValues != nil && observabilityStackInstanceValues.TempoHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("TempoHelmValues and TempoHelmValuesDocument cannot both be set"))
	}

	// ensure otel agent helm values and document are not both set
	if observabilityStackInstanceValues.OtelAgentHelmValues != nil && observabilityStackInstanceValues.OtelAgentHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("OtelAgentHelmValues and OtelAgentHelmValuesDocument cannot both be set"))
	}

	// ensure otel gateway helm values and document are not both set
	if observabilityStackInstanceValues.OtelGatewayHelmValues != nil && observabilityStackInstanceValues.OtelGatewayHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("OtelGatewayHelmValues and OtelGatewayHelmValuesDocument cannot both be set"))
	}

	// ensure otel browser relay helm values and document are not both set
	if observabilityStackInstanceValues.OtelBrowserRelayHelmValues != nil && observabilityStackInstanceValues.OtelBrowserRelayHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("OtelBrowserRelayHelmValues and OtelBrowserRelayHelmValuesDocument cannot both be set"))
	}

	return multiError.Error()
}
