// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"errors"
	"fmt"
	"net/http"

	api_v0 "github.com/threeport/threeport/pkg/api/v0"
	client_v0 "github.com/threeport/threeport/pkg/client/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
)

// ObservabilityStackDefinitionConfig is a config abstraction for the ObservabilityStackDefinition API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type ObservabilityStackDefinitionConfig struct {
	ObservabilityStackDefinition ObservabilityStackDefinitionValues
}

// ObservabilityStackDefinitionValues contains all the attributes needed to manage
// the ObservabilityStackDefinition API object.
type ObservabilityStackDefinitionValues struct {
	Name                                  *string `json:",omitempty"`
	GrafanaHelmValues                     *string `json:",omitempty"`
	GrafanaHelmValuesDocument             *string `json:",omitempty"`
	KubePrometheusStackHelmValues         *string `json:",omitempty"`
	KubePrometheusStackHelmValuesDocument *string `json:",omitempty"`
	MimirHelmValues                       *string `json:",omitempty"`
	MimirHelmValuesDocument               *string `json:",omitempty"`
	LokiHelmValues                        *string `json:",omitempty"`
	LokiHelmValuesDocument                *string `json:",omitempty"`
	TempoHelmValues                       *string `json:",omitempty"`
	TempoHelmValuesDocument               *string `json:",omitempty"`
	OtelAgentHelmValues                   *string `json:",omitempty"`
	OtelAgentHelmValuesDocument           *string `json:",omitempty"`
	OtelGatewayHelmValues                 *string `json:",omitempty"`
	OtelGatewayHelmValuesDocument         *string `json:",omitempty"`
	OtelBrowserRelayHelmValues            *string `json:",omitempty"`
	OtelBrowserRelayHelmValuesDocument    *string `json:",omitempty"`
	ObservabilityConfigPath               *string `json:",omitempty"`
	Age                                   *string `json:",omitempty"`
}

// Get gets observability stack definitions from the Threeport API.
// If the name is set in the ObservabilityStackDefinitionValues, it will return the observability stack definition with that name.
// If the name is not set, it will return all observability stack definitions.
func (o *ObservabilityStackDefinitionConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]ObservabilityStackDefinitionConfig, error) {
	observabilityStackDefinitionValues := o.ObservabilityStackDefinition
	// get API objects
	var observabilityStackDefinitions *[]api_v0.ObservabilityStackDefinition
	switch {
	// if name is provided, get observability stack definition by name
	case observabilityStackDefinitionValues.Name != nil:
		observabilityStackDefinition, err := client_v0.GetObservabilityStackDefinitionByName(apiClient, apiEndpoint, *observabilityStackDefinitionValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get observability stack definition with name %s: %w", *observabilityStackDefinitionValues.Name, err)
		}
		observabilityStackDefinitions = &[]api_v0.ObservabilityStackDefinition{*observabilityStackDefinition}
	// get all observability stack definitions
	default:
		allObservabilityStackDefinitions, err := client_v0.GetObservabilityStackDefinitions(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get observability stack definitions from Threeport API: %w", err)
		}
		observabilityStackDefinitions = allObservabilityStackDefinitions
	}

	// assemble config objects from API objects
	var observabilityStackDefinitionConfigs []ObservabilityStackDefinitionConfig
	for _, observabilityStackDefinition := range *observabilityStackDefinitions {
		observabilityStackDefinitionConfig := ObservabilityStackDefinitionConfig{
			ObservabilityStackDefinition: ObservabilityStackDefinitionValues{
				Name:                                  observabilityStackDefinition.Name,
				GrafanaHelmValuesDocument:             observabilityStackDefinition.GrafanaHelmValuesDocument,
				KubePrometheusStackHelmValuesDocument: observabilityStackDefinition.KubePrometheusStackHelmValuesDocument,
				MimirHelmValuesDocument:               observabilityStackDefinition.MimirHelmValuesDocument,
				LokiHelmValuesDocument:                observabilityStackDefinition.LokiHelmValuesDocument,
				TempoHelmValuesDocument:               observabilityStackDefinition.TempoHelmValuesDocument,
				OtelAgentHelmValuesDocument:           observabilityStackDefinition.OtelAgentHelmValuesDocument,
				OtelGatewayHelmValuesDocument:         observabilityStackDefinition.OtelGatewayHelmValuesDocument,
				OtelBrowserRelayHelmValuesDocument:    observabilityStackDefinition.OtelBrowserRelayHelmValuesDocument,
				Age:                                   util.Ptr(util.GetAgeFormatted(observabilityStackDefinition.CreatedAt)),
			},
		}
		observabilityStackDefinitionConfigs = append(observabilityStackDefinitionConfigs, observabilityStackDefinitionConfig)
	}

	return &observabilityStackDefinitionConfigs, nil
}

// Create creates a observability stack definition in the Threeport API.
func (o *ObservabilityStackDefinitionConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*ObservabilityStackDefinitionConfig, error) {
	observabilityStackDefinitionValues := o.ObservabilityStackDefinition
	// validate config
	if err := o.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for observability stack definition with name %s: %w", *observabilityStackDefinitionValues.Name, err)
	}

	// construct observability stack definition object
	observabilityStackDefinition := &api_v0.ObservabilityStackDefinition{
		Definition: api_v0.Definition{
			Name: observabilityStackDefinitionValues.Name,
		},
	}

	// set grafana helm values if present
	grafanaHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.GrafanaHelmValues,
		observabilityStackDefinitionValues.GrafanaHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get grafana values document from path: %w", err)
	}
	observabilityStackDefinition.GrafanaHelmValuesDocument = grafanaHelmValuesDocument

	// set kube-prometheus-stack helm values if present
	kubePrometheusStackHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.KubePrometheusStackHelmValues,
		observabilityStackDefinitionValues.KubePrometheusStackHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kube-prometheus-stack values document from path: %w", err)
	}
	observabilityStackDefinition.KubePrometheusStackHelmValuesDocument = kubePrometheusStackHelmValuesDocument

	// set mimir helm values if present
	mimirHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.MimirHelmValues,
		observabilityStackDefinitionValues.MimirHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get mimir values document from path: %w", err)
	}
	observabilityStackDefinition.MimirHelmValuesDocument = mimirHelmValuesDocument

	// set loki helm values if present
	lokiHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.LokiHelmValues,
		observabilityStackDefinitionValues.LokiHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get loki values document from path: %w", err)
	}
	observabilityStackDefinition.LokiHelmValuesDocument = lokiHelmValuesDocument

	// set tempo helm values if present
	tempoHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.TempoHelmValues,
		observabilityStackDefinitionValues.TempoHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get tempo values document from path: %w", err)
	}
	observabilityStackDefinition.TempoHelmValuesDocument = tempoHelmValuesDocument

	// set otel agent helm values if present
	otelAgentHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.OtelAgentHelmValues,
		observabilityStackDefinitionValues.OtelAgentHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get otel agent values document from path: %w", err)
	}
	observabilityStackDefinition.OtelAgentHelmValuesDocument = otelAgentHelmValuesDocument

	// set otel gateway helm values if present
	otelGatewayHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.OtelGatewayHelmValues,
		observabilityStackDefinitionValues.OtelGatewayHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get otel gateway values document from path: %w", err)
	}
	observabilityStackDefinition.OtelGatewayHelmValuesDocument = otelGatewayHelmValuesDocument

	// set otel browser relay helm values if present
	otelBrowserRelayHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.OtelBrowserRelayHelmValues,
		observabilityStackDefinitionValues.OtelBrowserRelayHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get otel browser relay values document from path: %w", err)
	}
	observabilityStackDefinition.OtelBrowserRelayHelmValuesDocument = otelBrowserRelayHelmValuesDocument

	// create observability stack definition
	createdObservabilityStackDefinition, err := client_v0.CreateObservabilityStackDefinition(
		apiClient,
		apiEndpoint,
		observabilityStackDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create observability stack definition in threeport API: %w", err)
	}

	// construct observability stack definition config
	createdObservabilityStackDefinitionConfig := &ObservabilityStackDefinitionConfig{
		ObservabilityStackDefinition: ObservabilityStackDefinitionValues{
			Age:                                   util.Ptr(util.GetAgeFormatted(createdObservabilityStackDefinition.CreatedAt)),
			Name:                                  createdObservabilityStackDefinition.Name,
			GrafanaHelmValues:                     observabilityStackDefinitionValues.GrafanaHelmValues,
			GrafanaHelmValuesDocument:             createdObservabilityStackDefinition.GrafanaHelmValuesDocument,
			KubePrometheusStackHelmValues:         observabilityStackDefinitionValues.KubePrometheusStackHelmValues,
			KubePrometheusStackHelmValuesDocument: createdObservabilityStackDefinition.KubePrometheusStackHelmValuesDocument,
			MimirHelmValues:                       observabilityStackDefinitionValues.MimirHelmValues,
			MimirHelmValuesDocument:               createdObservabilityStackDefinition.MimirHelmValuesDocument,
			LokiHelmValues:                        observabilityStackDefinitionValues.LokiHelmValues,
			LokiHelmValuesDocument:                createdObservabilityStackDefinition.LokiHelmValuesDocument,
			TempoHelmValues:                       observabilityStackDefinitionValues.TempoHelmValues,
			TempoHelmValuesDocument:               createdObservabilityStackDefinition.TempoHelmValuesDocument,
			OtelAgentHelmValues:                   observabilityStackDefinitionValues.OtelAgentHelmValues,
			OtelAgentHelmValuesDocument:           createdObservabilityStackDefinition.OtelAgentHelmValuesDocument,
			OtelGatewayHelmValues:                 observabilityStackDefinitionValues.OtelGatewayHelmValues,
			OtelGatewayHelmValuesDocument:         createdObservabilityStackDefinition.OtelGatewayHelmValuesDocument,
			OtelBrowserRelayHelmValues:            observabilityStackDefinitionValues.OtelBrowserRelayHelmValues,
			OtelBrowserRelayHelmValuesDocument:    createdObservabilityStackDefinition.OtelBrowserRelayHelmValuesDocument,
			ObservabilityConfigPath:               observabilityStackDefinitionValues.ObservabilityConfigPath,
		},
	}

	return createdObservabilityStackDefinitionConfig, nil
}

// Replace updates the entire observability stack definition object in the Threeport API.
// This is a full replacement of all fields in the observability stack definition object.
// This function takes a name parameter to identify the observability stack definition to replace.
// This allows a different name to be provided in the values object for name changes.
func (o *ObservabilityStackDefinitionConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*ObservabilityStackDefinitionConfig, error) {
	observabilityStackDefinitionValues := o.ObservabilityStackDefinition
	// validate config
	if err := o.Validate(); err != nil {
		return nil, fmt.Errorf("invalid observability stack definition config: %w", err)
	}

	// get existing observability stack definition by name
	existingObservabilityStackDefinition, err := client_v0.GetObservabilityStackDefinitionByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find observability stack definition with name %s: %w", name, err)
	}

	// construct updated observability stack definition object
	updatedObservabilityStackDefinition := &api_v0.ObservabilityStackDefinition{
		Common: api_v0.Common{
			ID: existingObservabilityStackDefinition.ID,
		},
		Definition: api_v0.Definition{
			Name: observabilityStackDefinitionValues.Name,
		},
	}

	// set grafana helm values if present
	grafanaHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.GrafanaHelmValues,
		observabilityStackDefinitionValues.GrafanaHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get grafana values document from path: %w", err)
	}
	updatedObservabilityStackDefinition.GrafanaHelmValuesDocument = grafanaHelmValuesDocument

	// set kube-prometheus-stack helm values if present
	kubePrometheusStackHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.KubePrometheusStackHelmValues,
		observabilityStackDefinitionValues.KubePrometheusStackHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kube-prometheus-stack values document from path: %w", err)
	}
	updatedObservabilityStackDefinition.KubePrometheusStackHelmValuesDocument = kubePrometheusStackHelmValuesDocument

	// set mimir helm values if present
	mimirHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.MimirHelmValues,
		observabilityStackDefinitionValues.MimirHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get mimir values document from path: %w", err)
	}
	updatedObservabilityStackDefinition.MimirHelmValuesDocument = mimirHelmValuesDocument

	// set loki helm values if present
	lokiHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.LokiHelmValues,
		observabilityStackDefinitionValues.LokiHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get loki values document from path: %w", err)
	}
	updatedObservabilityStackDefinition.LokiHelmValuesDocument = lokiHelmValuesDocument

	// set tempo helm values if present
	tempoHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.TempoHelmValues,
		observabilityStackDefinitionValues.TempoHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get tempo values document from path: %w", err)
	}
	updatedObservabilityStackDefinition.TempoHelmValuesDocument = tempoHelmValuesDocument

	// set otel agent helm values if present
	otelAgentHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.OtelAgentHelmValues,
		observabilityStackDefinitionValues.OtelAgentHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get otel agent values document from path: %w", err)
	}
	updatedObservabilityStackDefinition.OtelAgentHelmValuesDocument = otelAgentHelmValuesDocument

	// set otel gateway helm values if present
	otelGatewayHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.OtelGatewayHelmValues,
		observabilityStackDefinitionValues.OtelGatewayHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get otel gateway values document from path: %w", err)
	}
	updatedObservabilityStackDefinition.OtelGatewayHelmValuesDocument = otelGatewayHelmValuesDocument

	// set otel browser relay helm values if present
	otelBrowserRelayHelmValuesDocument, err := GetValuesFromDocumentOrInline(
		observabilityStackDefinitionValues.OtelBrowserRelayHelmValues,
		observabilityStackDefinitionValues.OtelBrowserRelayHelmValuesDocument,
		observabilityStackDefinitionValues.ObservabilityConfigPath,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get otel browser relay values document from path: %w", err)
	}
	updatedObservabilityStackDefinition.OtelBrowserRelayHelmValuesDocument = otelBrowserRelayHelmValuesDocument

	// replace observability stack definition
	replacedObservabilityStackDefinition, err := client_v0.ReplaceObservabilityStackDefinition(
		apiClient,
		apiEndpoint,
		updatedObservabilityStackDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace observability stack definition in threeport API: %w", err)
	}

	// construct updated observability stack definition config
	updatedObservabilityStackDefinitionConfig := &ObservabilityStackDefinitionConfig{
		ObservabilityStackDefinition: ObservabilityStackDefinitionValues{
			Age:                                   util.Ptr(util.GetAgeFormatted(replacedObservabilityStackDefinition.CreatedAt)),
			Name:                                  replacedObservabilityStackDefinition.Name,
			GrafanaHelmValues:                     observabilityStackDefinitionValues.GrafanaHelmValues,
			GrafanaHelmValuesDocument:             replacedObservabilityStackDefinition.GrafanaHelmValuesDocument,
			KubePrometheusStackHelmValues:         observabilityStackDefinitionValues.KubePrometheusStackHelmValues,
			KubePrometheusStackHelmValuesDocument: replacedObservabilityStackDefinition.KubePrometheusStackHelmValuesDocument,
			MimirHelmValues:                       observabilityStackDefinitionValues.MimirHelmValues,
			MimirHelmValuesDocument:               replacedObservabilityStackDefinition.MimirHelmValuesDocument,
			LokiHelmValues:                        observabilityStackDefinitionValues.LokiHelmValues,
			LokiHelmValuesDocument:                replacedObservabilityStackDefinition.LokiHelmValuesDocument,
			TempoHelmValues:                       observabilityStackDefinitionValues.TempoHelmValues,
			TempoHelmValuesDocument:               replacedObservabilityStackDefinition.TempoHelmValuesDocument,
			OtelAgentHelmValues:                   observabilityStackDefinitionValues.OtelAgentHelmValues,
			OtelAgentHelmValuesDocument:           replacedObservabilityStackDefinition.OtelAgentHelmValuesDocument,
			OtelGatewayHelmValues:                 observabilityStackDefinitionValues.OtelGatewayHelmValues,
			OtelGatewayHelmValuesDocument:         replacedObservabilityStackDefinition.OtelGatewayHelmValuesDocument,
			OtelBrowserRelayHelmValues:            observabilityStackDefinitionValues.OtelBrowserRelayHelmValues,
			OtelBrowserRelayHelmValuesDocument:    replacedObservabilityStackDefinition.OtelBrowserRelayHelmValuesDocument,
			ObservabilityConfigPath:               observabilityStackDefinitionValues.ObservabilityConfigPath,
		},
	}

	return updatedObservabilityStackDefinitionConfig, nil
}

// Delete deletes a observability stack definition from the Threeport API.
func (o *ObservabilityStackDefinitionConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*ObservabilityStackDefinitionConfig, error) {
	observabilityStackDefinitionValues := o.ObservabilityStackDefinition
	// get observability stack definition by name
	observabilityStackDefinition, err := client_v0.GetObservabilityStackDefinitionByName(
		apiClient,
		apiEndpoint,
		*observabilityStackDefinitionValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find observability stack definition with name %s: %w", *observabilityStackDefinitionValues.Name, err)
	}

	// delete observability stack definition
	deletedObservabilityStackDefinition, err := client_v0.DeleteObservabilityStackDefinition(
		apiClient,
		apiEndpoint,
		*observabilityStackDefinition.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete observability stack definition from Threeport API: %w", err)
	}

	// construct deleted observability stack definition config
	deletedObservabilityStackDefinitionConfig := &ObservabilityStackDefinitionConfig{
		ObservabilityStackDefinition: ObservabilityStackDefinitionValues{
			Name:                                  deletedObservabilityStackDefinition.Name,
			GrafanaHelmValuesDocument:             deletedObservabilityStackDefinition.GrafanaHelmValuesDocument,
			KubePrometheusStackHelmValuesDocument: deletedObservabilityStackDefinition.KubePrometheusStackHelmValuesDocument,
			MimirHelmValuesDocument:               deletedObservabilityStackDefinition.MimirHelmValuesDocument,
			LokiHelmValuesDocument:                deletedObservabilityStackDefinition.LokiHelmValuesDocument,
			TempoHelmValuesDocument:               deletedObservabilityStackDefinition.TempoHelmValuesDocument,
			OtelAgentHelmValuesDocument:           deletedObservabilityStackDefinition.OtelAgentHelmValuesDocument,
			OtelGatewayHelmValuesDocument:         deletedObservabilityStackDefinition.OtelGatewayHelmValuesDocument,
			OtelBrowserRelayHelmValuesDocument:    deletedObservabilityStackDefinition.OtelBrowserRelayHelmValuesDocument,
		},
	}

	return deletedObservabilityStackDefinitionConfig, nil
}

// Validate validates inputs to create observability stack definitions.
func (o *ObservabilityStackDefinitionConfig) Validate() error {
	observabilityStackDefinitionValues := o.ObservabilityStackDefinition
	multiError := util.MultiError{}

	// ensure name is set
	if observabilityStackDefinitionValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// ensure grafana helm values and document are not both set
	if observabilityStackDefinitionValues.GrafanaHelmValues != nil && observabilityStackDefinitionValues.GrafanaHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("GrafanaHelmValues and GrafanaHelmValuesDocument cannot both be set"))
	}

	// ensure kube-prometheus-stack helm values and document are not both set
	if observabilityStackDefinitionValues.KubePrometheusStackHelmValues != nil && observabilityStackDefinitionValues.KubePrometheusStackHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("KubePrometheusStackHelmValues and KubePrometheusStackHelmValuesDocument cannot both be set"))
	}

	// ensure mimir helm values and document are not both set
	if observabilityStackDefinitionValues.MimirHelmValues != nil && observabilityStackDefinitionValues.MimirHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("MimirHelmValues and MimirHelmValuesDocument cannot both be set"))
	}

	// ensure loki helm values and document are not both set
	if observabilityStackDefinitionValues.LokiHelmValues != nil && observabilityStackDefinitionValues.LokiHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("LokiHelmValues and LokiHelmValuesDocument cannot both be set"))
	}

	// ensure tempo helm values and document are not both set
	if observabilityStackDefinitionValues.TempoHelmValues != nil && observabilityStackDefinitionValues.TempoHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("TempoHelmValues and TempoHelmValuesDocument cannot both be set"))
	}

	// ensure otel agent helm values and document are not both set
	if observabilityStackDefinitionValues.OtelAgentHelmValues != nil && observabilityStackDefinitionValues.OtelAgentHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("OtelAgentHelmValues and OtelAgentHelmValuesDocument cannot both be set"))
	}

	// ensure otel gateway helm values and document are not both set
	if observabilityStackDefinitionValues.OtelGatewayHelmValues != nil && observabilityStackDefinitionValues.OtelGatewayHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("OtelGatewayHelmValues and OtelGatewayHelmValuesDocument cannot both be set"))
	}

	// ensure otel browser relay helm values and document are not both set
	if observabilityStackDefinitionValues.OtelBrowserRelayHelmValues != nil && observabilityStackDefinitionValues.OtelBrowserRelayHelmValuesDocument != nil {
		multiError.AppendError(fmt.Errorf("OtelBrowserRelayHelmValues and OtelBrowserRelayHelmValuesDocument cannot both be set"))
	}

	return multiError.Error()
}
